### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ahubaili82** [anilbeesetti/nextplayer#1018]
The button to delete a video overlaps with navigation buttons making it difficult to delete a video from the app.

![IMG_20240728_192302.jpg](https://github.com/user-attachments/assets/9a0bf9c7-a866-4c7b-b160-c3f4b9234dc3)

 - Device: [Oppo A5s]
 - Android version: [8.1.0]
 - App version: [0.11.1]

**Comment by anilbeesetti** [comment]
Hey @ahubaili82 can you test this build and let me know if the issue still exists https://github.com/anilbeesetti/nextplayer/actions/runs/10130678078/artifacts/1747925653

**Comment by ahubaili82** [comment]
> Hey @ahubaili82 can you test this build and let me know if the issue still exists https://github.com/anilbeesetti/nextplayer/actions/runs/10130678078/artifacts/1747925653

The issue has been resolved.
