### ISSUE TITLE
[FEATURE REQUEST] Ability to set double tap increment

### ISSUE THREAD

**Issue by shreyas-a-s** [anilbeesetti/nextplayer#1184]
Just like having seek increment, it would be great to be able to set increment while double tapping to fast-forward/rewind. The default, which is 10 seconds, is pretty ok but I would like to set it lower to 5s and the feature is available on other apps.

Thanks in advance.

**Comment by idrakahmedrohan** [comment]
It is already available in the Settings > Player > Seek increment 

It can be set between 1s - 60s
![Screenshot_2024-12-30-21-02-09-956_dev anilbeesetti nextplayer-edit](https://github.com/user-attachments/assets/e5aabaf6-4d27-46d9-b2b2-8a9088e3f90e)

**Comment by shreyas-a-s** [comment]
Oh, my mistake. Sorry. I thought it controlled the time increment when using the seek bar.

Thanks for clarification.

Closing the issue.
