### ISSUE TITLE
Request: Seeking Help to Create Application Icon

### ISSUE THREAD

**Issue by anilbeesetti** [anilbeesetti/nextplayer#243]
As a non-designer, I lack the necessary skills and knowledge to create a good-looking application icon. By seeking assistance from the community, I hope to leverage the expertise and creativity of talented individuals who can contribute to the visual appeal and branding of the app.

**Comment by carkks** [comment]
![IMG_20230520_171139.png](https://github.com/anilbeesetti/nextplayer/assets/82451852/65787284-fe07-4f58-9d83-d4297aab46c4)

![IMG_20230520_171557.png](https://github.com/anilbeesetti/nextplayer/assets/82451852/a2c90613-2e37-4d60-8e45-378f9d3acdf3)

I got the colors based on the interface color **without dynamic color**, I'll see some more icons I can do here.

But, if you like it, can you make the icon change color based on the material you?

**Comment by anilbeesetti** [comment]
Great work! However, don't you think the app icon is too generic? I believe it could greatly benefit from a more distinctive design. What is your opinion on this matter?

**Comment by carkks** [comment]
> Great work! However, don't you think the app icon is too generic? I believe it could greatly benefit from a more distinctive design. What is your opinion on this matter?

![IMG_20230521_082911.png](https://github.com/anilbeesetti/nextplayer/assets/82451852/099ba590-2899-4e84-b35c-82ac508d8608)

I can still do more, but what do you think?

**Comment by anilbeesetti** [comment]
That's a good suggestion. However, could you please consider trying lighter colors? I feel that the contrast between the colors used is not sufficient. Thank you for your understanding. Furthermore, try applying the same concept to the initially proposed icon.

**Comment by carkks** [comment]
![IMG_20230521_102758.png](https://github.com/anilbeesetti/nextplayer/assets/82451852/7de2c99b-b550-41fa-b3aa-efe01c0a16df)


This one is more of a sample, however, I have several ideas for icons, I'm going to make a "pack" of 10 icons here, then you tell me which one you found most interesting, and point out what can be modified.

As the name of the app is **"Next Player"**, I thought of making an icon with a double arrow, it would be interesting, what do you think? Lol 😀

**Comment by anilbeesetti** [comment]
That sounds good

**Comment by Sadwhy3** [comment]
Making it look like a never ending optical illusion would be pretty cool.

**Comment by Sadwhy3** [comment]
Like these
![images (3)](https://github.com/anilbeesetti/nextplayer/assets/99601717/08b7fb5a-7498-484e-bccd-036d47b4f663)

**Comment by carkks** [comment]
> Like these
> ![images (3)](https://github.com/anilbeesetti/nextplayer/assets/99601717/08b7fb5a-7498-484e-bccd-036d47b4f663)
> 

Hm, it's cool
but if you change the color palette to the already integrated color it would be even better, I'll see if I make one in this style

**Comment by Sadwhy3** [comment]
I'm no artist. I just pulled this off of Google in hopes to make a suggestion.

**Comment by carkks** [comment]
> I'm no artist. I just pulled this off of Google in hopes to make a suggestion.

![IMG_20230529_142855.png](https://github.com/anilbeesetti/nextplayer/assets/82451852/d29ec84d-7b73-4e37-a790-8662f1d2997e)

This was ridiculously difficult to do, because I got lost all the time, and to keep the 3D structure, I had to add 20 layers (Note: I was lazy, I did everything on my cell phone).

**Comment by carkks** [comment]
![SmartSelect_20230529_150007_Photo Editor.gif](https://github.com/anilbeesetti/nextplayer/assets/82451852/534e6fa1-8584-4372-914c-e509d8d7eeea)
I think it's good...
![IMG_20230529_150220.png](https://github.com/anilbeesetti/nextplayer/assets/82451852/b37469ea-37a7-4354-bd84-f9ae77f44395)

**Comment by anilbeesetti** [comment]
Hi @srcarkk, I really appreciate the icons you created. They are quite good. However, I have a suggestion to further improve the icons. I believe they would look even better if there was a clear separation in color contrast between the foreground and background elements. Could you please show me an example of the first icon you proposed with this adjustment? Thank you!

**Comment by carkks** [comment]
> Hi @srcarkk, I really appreciate the icons you created. They are quite good. However, I have a suggestion to further improve the icons. I believe they would look even better if there was a clear separation in color contrast between the foreground and background elements. Could you please show me an example of the first icon you proposed with this adjustment? Thank you!

![IMG_20230530_061116.png](https://github.com/anilbeesetti/nextplayer/assets/82451852/f38e33f2-feab-487c-89cf-59636f821f80)

![IMG_20230530_061231.png](https://github.com/anilbeesetti/nextplayer/assets/82451852/d884a39c-8fbf-413f-a475-2c58b9644f37)

![IMG_20230530_060642.png](https://github.com/anilbeesetti/nextplayer/assets/82451852/87d60b73-9e17-4e29-b8ec-97535cc07529)

![IMG_20230530_060955.png](https://github.com/anilbeesetti/nextplayer/assets/82451852/985c0348-8e64-49c0-9841-36f204381c34)

![IMG_20230530_061628.png](https://github.com/anilbeesetti/nextplayer/assets/82451852/bcdf563e-9b3a-4895-8eeb-2402241e8378)

Like this?  What do you think?

**Comment by anilbeesetti** [comment]
Yes. These are good 
![](https://user-images.githubusercontent.com/82451852/239707706-65787284-fe07-4f58-9d83-d4297aab46c4.png)

![](https://user-images.githubusercontent.com/82451852/241912084-f38e33f2-feab-487c-89cf-59636f821f80.png)


It would be extremely helpful if you could create the first icon using the colors from the top section of the second icon. Since I'm considering finalizing the shape of the first icon for the upcoming release, having this version with the colors would greatly assist me. Additionally, I would also appreciate having the icon in a light theme variant. Thank you in advance for your support!

**Comment by merahul** [comment]
You can give it a try to this one.
![IMG_20230530_183804_674](https://github.com/anilbeesetti/nextplayer/assets/21130883/1dadb91f-a686-43c7-9a8c-7bcd0e519df0)
[Video_Next.zip](https://github.com/anilbeesetti/nextplayer/files/11600216/Video_Next.zip)

**Comment by merahul** [comment]
Could you please share the latest build after all these changes?

**Comment by carkks** [comment]
> Yes. These are good 
> ![](https://user-images.githubusercontent.com/82451852/239707706-65787284-fe07-4f58-9d83-d4297aab46c4.png)
> 
> ![](https://user-images.githubusercontent.com/82451852/241912084-f38e33f2-feab-487c-89cf-59636f821f80.png)
> 
> 
> It would be extremely helpful if you could create the first icon using the colors from the top section of the second icon. Since I'm considering finalizing the shape of the first icon for the upcoming release, having this version with the colors would greatly assist me. Additionally, I would also appreciate having the icon in a light theme variant. Thank you in advance for your support!

![IMG_20230530_120251.png](https://github.com/anilbeesetti/nextplayer/assets/82451852/88cac579-ba8f-4164-b04e-e43569fa8a6c)

![IMG_20230530_120617.png](https://github.com/anilbeesetti/nextplayer/assets/82451852/4d31a16b-6bbc-4147-84ed-e73a3b1baa7a)



Like this?

**Comment by anilbeesetti** [comment]
Yes! These icons are good. Could you kindly share the files with me so that I can utilize them as icons for the app?

**Comment by carkks** [comment]
> Yes! These icons are good. Could you kindly share the files with me so that I can utilize them as icons for the app?

Ye, you can use

**Comment by anilbeesetti** [comment]
Hi @srcarkk, I wanted to express my appreciation for the icons you created. I took the liberty of making some modifications to one of them to better align with my liking, and I have now utilized it as the application icon. I truly value the time and effort you invested in creating these icons. Thank you once again.

**Comment by XelXen** [comment]
Hi, I think I'm late but I also made an app icon and created an issue [here](https://github.com/anilbeesetti/nextplayer/issues/372)
