### ISSUE TITLE
BUG - videos take a long time to open (AV1 codec)

### ISSUE THREAD

**Issue by Wjxfi** [anilbeesetti/nextplayer#244]
First, after I clicked on the video, the app froze for 4 seconds. Then a black screen appears, and after another 4 seconds a dialog box appears saying that the app is "not responding". If I press wait, the endless black screen continues. 

`miui, android 12, f-droid 0.1.0`

Also, when I try to open a folder with more than 200 videos, I have to wait 2 second for it to open. This is also a waiting problem.

**Comment by anilbeesetti** [comment]
- Thank you for bringing the issue to my attention. I have made the necessary modifications to address the player black screen problem in the app. You can find the details in pr #256.
- To verify if the issue has been resolved, I kindly request you to test the update by downloading the artifact from the following link: https://github.com/anilbeesetti/nextplayer/actions/runs/5037260087. Please let me know if this resolves the player black screen issue.

`Please note that the APK is currently in debug mode, which means that the app may operate at a slower pace compared to the release version.`
