### ISSUE TITLE
I want to help with Spanish translation

### ISSUE THREAD

**Issue by cyanwolfg** [anilbeesetti/nextplayer#246]
Hi, I have been waiting for a long time for an open source video player alternative with a good design. I understand that the development of this app is early, even so it already looks very good.

I would like to help with the translation of the application to Spanish, I don't know much about programming but I have helped before in the translation of other applications.

How could I help with the translation?

**Comment by anilbeesetti** [comment]
Once the Weblate setup is complete, I will provide you with the necessary information.

**Comment by anilbeesetti** [comment]
Hey @cyanwolfg, I've set up a [Weblate](https://hosted.weblate.org/engage/next-player/) project for translation. Now you can help translate it into Spanish. Thank you for showing interest in the project

**Comment by cyanwolfg** [comment]
Thanks to you for share your app.
