### ISSUE TITLE
[Request] Pip

### ISSUE THREAD

**Issue by ghost** [anilbeesetti/nextplayer#250]
We need the ability to watch videos in a window, as in "Just player"

**Comment by brnwlshubh** [comment]
@anilbeesetti Any Update?

**Comment by anilbeesetti** [comment]
Unfortunately this feature's going take some more time

**Comment by Pentaphon** [comment]
@anilbeesetti https://github.com/anilbeesetti/nextplayer/pull/646 just landed

**Comment by rohitghali** [comment]
How do I get into pip mode? Tried swiping home. Didn't work. Searched in settings, no option. No button for it also while playing a video.

**Comment by Pentaphon** [comment]
> How do I get into pip mode? Tried swiping home. Didn't work. Searched in settings, no option. No button for it also while playing a video.

You have to wait for the next release.

**Comment by rohitghali** [comment]
Downloaded the latest debug version. Thanks.

**Comment by anilbeesetti** [comment]
- feature added in PR #646
