### ISSUE TITLE
[Request] Listen in the background

### ISSUE THREAD

**Issue by ghost** [anilbeesetti/nextplayer#251]
Continue playback when the screen is off

**Comment by merahul** [comment]
I agree, this is very useful feature.

**Comment by Pentaphon** [comment]
Yes, this is something that Just Player is missing. We need a notification running to control the background play as well.

**Comment by Warden20** [comment]
Any update?

**Comment by Pentaphon** [comment]
> Any update?

PIP support has been added to https://github.com/anilbeesetti/nextplayer/releases/tag/v0.11.0 and now we just need to wait for notification support before background play can be added.

**Comment by ivan-ivory** [comment]
Any update?

**Comment by Pentaphon** [comment]
@ivan-ivory it looks like the dev is starting to work on this at https://github.com/anilbeesetti/nextplayer/pull/1103

**Comment by anilbeesetti** [comment]
- Done in #1103

**Comment by ivan-ivory** [comment]
Will there be a release before the new year?
