### ISSUE TITLE
[Request] Choice of button locations

### ISSUE THREAD

**Issue by ghost** [anilbeesetti/nextplayer#252]
I am not very comfortable when these buttons are on the left, so I propose to make an option where you can choose where they are on the right or left
![IMG_20230520_212409_408](https://github.com/anilbeesetti/nextplayer/assets/51048550/70b40b4b-2c72-485f-815e-d1dabd242c9c)

**Comment by Alyaqdhans** [comment]
I agree, this is very important feature. You can also make it so the user can change if the buttons left or right and their postion order, it can be made like a list and on each button there is combo box to choose left or right and each button can be dragged to change order.

something like this if possible or similar (by the way I think minimize player is a must on the right)
![image](https://github.com/anilbeesetti/nextplayer/assets/58079015/1189da87-fa8e-4528-95d9-f45a98a409a3)

**Comment by Alyaqdhans** [comment]
Actually, the easiest option is to make a fixed button places.
lets say 2 left and 2 right, and then make an option in settings to choose what users want in that place.
It can also be none!
