### ISSUE TITLE
I would like to help translate the app into Chinese (Simplified) （我希望可以帮忙汉化这个应用）

### ISSUE THREAD

**Issue by ygxbnet** [anilbeesetti/nextplayer#270]
Hello, I have been using this app for some time, and although it is not yet very comprehensive, but I really like it. The only regret is that it doesn't have Chinese, I want it to become better.

So can I help translate it into Simplified Chinese?
How should I do?

**Comment by ygxbnet** [comment]
I translated with [Weblate](https://hosted.weblate.org/projects/next-player/android-strings-core/zh_Hans/)

[![翻译状态](https://hosted.weblate.org/widgets/next-player/-/multi-auto.svg)](https://hosted.weblate.org/engage/next-player/)

Hope it can be merged quickly, Thanks you!
Hopefully, this project can get better and better!

**Comment by anilbeesetti** [comment]
Thank you. I've merged your translations in pr #275
