### ISSUE TITLE
[Request] Additional extension support

### ISSUE THREAD

**Issue by brnwlshubh** [anilbeesetti/nextplayer#271]
Please add option to add any extra extension for video to see in app.
Ex. When I download any video from chrome the video extension contains ".crdownload" during download.

**Comment by anilbeesetti** [comment]
Unfortunately, the requested functionality cannot be achieved due to the current permissions being requested by the next player. To enable this feature, full storage permission would need to be granted, but this comes at the expense of privacy. Therefore, implementing this feature is not feasible.
