### ISSUE TITLE
Help with translation into Brazilian Portuguese

### ISSUE THREAD

**Issue by fosslatic** [anilbeesetti/nextplayer#274]
I would like to translate the app into Brazilian Portuguese

**Comment by anilbeesetti** [comment]
That's great to hear. You can help translate the app into Brazilian Portuguese using [weblate](https://hosted.weblate.org/projects/next-player)

**Comment by anilbeesetti** [comment]
Thank you for translating the app into Brazilian Portuguese. I've merged the translations in pr #275
