### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [anilbeesetti/nextplayer#277]
It is usually the case that people want GPLv3-_or-later_ when Weblate forces specifying one or the other.
"-only" means there is less flexibility in importing from other projects, and/or going AGPLv3, or possibly GPLv4 when or if that happens.

It can be changed in https://hosted.weblate.org/settings/next-player/android-strings-core/

Getting it adjusted now means not having to negotiate with multiple translators down the road. :)

Edit: There was also https://github.com/anilbeesetti/nextplayer/blob/09a13e6300ff5fdd0d560168812e9edf3ae0ab96/app/build.gradle.kts#L47

**Comment by anilbeesetti** [comment]
Thank you for the information. I have updated the license to GPLv3-or-later.

**Comment by anilbeesetti** [comment]
And  what about this: https://github.com/anilbeesetti/nextplayer/blob/09a13e6300ff5fdd0d560168812e9edf3ae0ab96/app/build.gradle.kts#L47
