### ISSUE TITLE
Internet access permission

### ISSUE THREAD

**Issue by VasilisKos** [anilbeesetti/nextplayer#282]
What's the internet permission needed for? 🤔

**Comment by anilbeesetti** [comment]
It's to play online streams

**Comment by VasilisKos** [comment]
> It's to play online streams

I see.
Let me take the opportunity to make some comments-requests. The app is REALLY fantastic mainly for two reasons. First, its beautiful Material You UI, and secondly and most important, its simplicity and minimalistic character. Please, do not make the mistake other developers have done, by starting simple and functional apps, and gradually made them more and more complex, by bloating them with useless features and settings. I say this because I see in those few reported issues that most feature requests are quite useless and nonsense! Please, do not change your initial approach. Keep it simple and working. Don't make it just another MX Player-wannabe app, like the thousands of that kind in Google Play. For me, after the todo features you want to add (and a nice icon), the app will be just perfect.

Now here are some suggestions:
1. When there's a subs file with the same name with the video file in the same folder, the subs track should be selected by default. Now you have to manually select it.
2. Add the option to select a subs track with any filename that's in the same folder with the video file. Now only subs of the exact same filename are selectable. 
3. When a subs filename has the [ ] characters, those characters are not displayed properly in the subs track selection menu.
4. Would it be possible to add in the file info of video files, in the media picker, the video resolution? There's space next to the video file size. Like e.g. 120MB, 1280x720.

That's for now. Keep up the really good work! ;)

P.S. I've translated the app in Greek.

**Comment by anilbeesetti** [comment]
Thank you for providing such a detailed feedback. You've truly made my day. Rest assured, I will try to maintain a balance between simplicity and functionality in the app. Additionally, I want to thank you for your contributions to the translations for the application.
