### ISSUE TITLE
[Request] Single Tap Pause/Resume feature.

### ISSUE THREAD

**Issue by matt873** [anilbeesetti/nextplayer#288]
Please add an option for pausing and resuming playback with a single tap on the screen.

**Comment by anilbeesetti** [comment]
Could you please provide further clarification on what you mean?

**Comment by matt873** [comment]
Later found in the playback settings double tap pause resume feature, so it is not that important to add this feature. But some people may need or like it.

**Comment by anilbeesetti** [comment]
Single tap to play pause conflicts with tap to show video controls. So this is not possible

**Comment by matt873** [comment]
Yeah, that's why I changed my mind about this Request. It's rather better to not implement this feature.

**Comment by anilbeesetti** [comment]
closing this as feature is not possible
