### ISSUE TITLE
[Request] Sort by Date

### ISSUE THREAD

**Issue by matt873** [anilbeesetti/nextplayer#289]
Please add an option for sorting videos by date/time.

**Comment by merahul** [comment]
Yeah correct it should be there.

**Comment by binoysankar** [comment]
Just now I installed latest version and immediately was searching for date filter and found it was missing. When you have large amount of video its quite difficult to scroll down towards the last. Would be convenient if you can add date sorting.
Btw very good player😊👍🏽
