### ISSUE TITLE
[BUG] Embedded Thumbnails not being Displayed

### ISSUE THREAD

**Issue by matt873** [anilbeesetti/nextplayer#293]
I have youtube videos downloaded with yt-dlp-application, YTDLnis, which have embedded YouTube thumbnails into videos. MX Player displays thumbnails correctly over videos but Next Player is not showing any thumbnails over videos.
![Screenshot_20230527-232549_1](https://github.com/anilbeesetti/nextplayer/assets/108935493/c05cb1b2-296b-4063-b032-701137530298)
![Screenshot_20230527-232539](https://github.com/anilbeesetti/nextplayer/assets/108935493/27bbb1ae-2d19-40f3-88ec-6dfaa9945bdc)

**Comment by matt873** [comment]
Embedded video thumbnails are still not shown in this release. These are different from a thumbnail separately downloaded to a video folder. In case of these, if I only move the video to a pc, the YouTube thumbnail on the video is still shown. I think it is embedded in the video and this is a feature of yt-dlp. I am using this feature on YTDLnis which provides easy to use UI for yt-dlp.
@anilbeesetti

**Comment by anilbeesetti** [comment]
Based on my understanding, it is not possible to embed images into videos, @matt873.

**Comment by anilbeesetti** [comment]
Upon reviewing the screenshots you shared of MX Player, it appears that the thumbnail is not embedded within the video. I also cross-checked this with YouTube, where I noticed that the thumbnail displayed differs from the one in the screenshots. To ensure accuracy, could you double-check the information once more.

**Comment by matt873** [comment]
> Based on my understanding, it is not possible to embed images into videos, @matt873.

I am not an expert but you can see the screenshot of the app YTDLnis. It does it by not saving the thumbnail to the download folder and I have checked the videos download folder, and there are no thumbnails present there. I also tested this feature by moving only the mp4 file to pc and it was showing the YouTube thumbnail as video cover art. You can try it yourself, it's a great app for downloading youtube videos and you might understand how this thing works.
![Screenshot_20230601-173642_1.png](https://github.com/anilbeesetti/nextplayer/assets/108935493/7ea90408-8409-47e5-84b1-4fbb149381ab)

**Comment by matt873** [comment]
> Upon reviewing the screenshots you shared of MX Player, it appears that the thumbnail is not embedded within the video. I also cross-checked this with YouTube, where I noticed that the thumbnail displayed differs from the one in the screenshots. To ensure accuracy, could you double-check the information once more.

I will check it again.

**Comment by matt873** [comment]
> Upon reviewing the screenshots you shared of MX Player, it appears that the thumbnail is not embedded within the video. I also cross-checked this with YouTube, where I noticed that the thumbnail displayed differs from the one in the screenshots. To ensure accuracy, could you double-check the information once more.

Here is one more video:

![Screenshot_20230601-175054.png](https://github.com/anilbeesetti/nextplayer/assets/108935493/d603eb84-2b40-41fa-b7a0-ea1268e637fc)

![Screenshot_20230601-174915.png](https://github.com/anilbeesetti/nextplayer/assets/108935493/5a1c1abf-f286-43f1-b82e-4cf005f64b1a)



![Screenshot_20230601-175344_1.png](https://github.com/anilbeesetti/nextplayer/assets/108935493/560ab573-ae4c-465b-a2fb-ca9b42ae2d76)

Order: Youtube, MX Player, Next Player

**Comment by matt873** [comment]
> > Upon reviewing the screenshots you shared of MX Player, it appears that the thumbnail is not embedded within the video. I also cross-checked this with YouTube, where I noticed that the thumbnail displayed differs from the one in the screenshots. To ensure accuracy, could you double-check the information once more.
> 
> Here is one more video:
> 
> ![Screenshot_20230601-175054.png](https://github.com/anilbeesetti/nextplayer/assets/108935493/d603eb84-2b40-41fa-b7a0-ea1268e637fc)
> 
> ![Screenshot_20230601-174915.png](https://github.com/anilbeesetti/nextplayer/assets/108935493/5a1c1abf-f286-43f1-b82e-4cf005f64b1a)
> 
> 
> 
> ![Screenshot_20230601-175344_1.png](https://github.com/anilbeesetti/nextplayer/assets/108935493/560ab573-ae4c-465b-a2fb-ca9b42ae2d76)
> 
> Order: Youtube, MX Player, Next Player
> 
> 

Here I moved just the video file to USB through an otg and also to another phone, and it's still showing the youtube thumbnail;
![Screenshot_20230601-180205.png](https://github.com/anilbeesetti/nextplayer/assets/108935493/540d92c8-2da2-45ec-99a0-9eac9d1a1e8b)

![PXL_20230601_130526137_1.jpg](https://github.com/anilbeesetti/nextplayer/assets/108935493/194a9707-92b7-48f9-a36c-7ce9e140d66f)

**Comment by anilbeesetti** [comment]
Great, I'll look into it asap.

**Comment by matt873** [comment]
> Great, I'll look into it asap.

Any Progress on it? It would be great if you can change the status of this issue to Open.

**Comment by matt873** [comment]
> Great, I'll look into it asap.

Any progress on it. Also the issue status is still closed. Can you please reopen it as it is prominent and basic issue.
