### ISSUE TITLE
[BUG] can't delete video from next player it self. 

### ISSUE THREAD

**Issue by merahul** [anilbeesetti/nextplayer#297]
**Describe the bug**
Thers is no option to delete video from next player.

**Comment by Archeix7** [comment]
Duplicate https://github.com/anilbeesetti/nextplayer/issues/258

**Comment by merahul** [comment]
No no it's not duplicate. I'm saying next player app is not allowing me to delete video. It should be there.

**Comment by ghost** [comment]
You have to edit your request so that in addition to the "delete" button it has additional options, such as "properties, change file name, edit, etc." And I will delete my comment in https://github.com/anilbeesetti/nextplayer/issues/258

**Comment by ShareASmile** [comment]
@anilbeesetti thanks for delete  in app itself function.

It deleted videos on my Samsung A225G android13, A50s Android10 fine, 

but does not delete video files on my old Vivo Y53 phone on Android 6 Funtouch 3. I tried many times to delete video in Movies folder (tried in others folders too)"it says deleted" but file remains there as before.
I checked Storage permission has been given.
