### ISSUE TITLE
Double tap to play and pause video

### ISSUE THREAD

**Issue by Dragonfly-30** [anilbeesetti/nextplayer#313]
.

**Comment by VasilisKos** [comment]
Useless feature. Keep the app simple.

**Comment by matt873** [comment]
> Useless feature. Keep the app simple.

It's up to the developer to decide whether it's useless or not and how he wants to keep this app. If you like a very simple app, there are many you can try. 
In between, this feature is already present in player settings.

**Comment by anilbeesetti** [comment]
This feature is already present. Check settings > player > double tap gesture

**Comment by VasilisKos** [comment]
> > Useless feature. Keep the app simple.
> 
> It's up to the developer to decide whether it's useless or not and how he wants to keep this app. If you like a very simple app, there are many you can try. In between, this feature is already present in playback settings.

And it's up to every user to comment on every posted issue. That's why github has this feature. It's the FOSS philosophy. That's how it makes progress. The final word is of course on the developer. After all, the source is available to anyone to add or remove features.
Anyway, as you said the feature is already there so this issue should be closed.

**Comment by matt873** [comment]
> > > Useless feature. Keep the app simple.
> > 
> > It's up to the developer to decide whether it's useless or not and how he wants to keep this app. If you like a very simple app, there are many you can try. In between, this feature is already present in playback settings.
> 
> And it's up to every user to comment on every posted issue. That's why github has this feature. It's the FOSS philosophy. That's how it makes progress. The final word is of course on the developer. After all, the source is available to anyone to add or remove features.
> Anyway, as you said the feature is already there so this issue should be closed.

I agree.

**Comment by Dragonfly-30** [comment]
> This feature is already present. Check settings > player > double tap gesture

Thank you, I found it. But it was a little bit   hard to find it "tapping on the icon to get the option". Haha.
