### ISSUE TITLE
[BUG] Subs not selectable when video opened through file manager

### ISSUE THREAD

**Issue by VasilisKos** [anilbeesetti/nextplayer#315]
Version 0.2.0 has a problem with subs. Tapping the subs selection button does nothing. Subs can't be selected. This didn't happen with 0.1.0. ☹️
Using Nokia 6.2, with stock Android 11.

**Comment by anilbeesetti** [comment]
It's working fine on my phone. Could you check that video has any subs at all

**Comment by VasilisKos** [comment]
> It's working fine on my phone. Could you check that video has any subs at all

I'm talking about external srt subs.

**Comment by anilbeesetti** [comment]
Could you send a screenshot of the folder containing video and subtitle in file manager. It would be helpful for me to debug the problem

**Comment by VasilisKos** [comment]
> Could you send a screenshot of the folder containing video and subtitle in file manager. It would be helpful for me to debug the problem

I think I found the bug. When the video is opened through the app's file picker there's no problem. But when the video is opened through a file manager, like my Solid Explorer, then the bug is present. Subs can't be selected.
I attach the screenshots you asked for, though I don't think it'll help.

![Screenshot_20230601-201518](https://github.com/anilbeesetti/nextplayer/assets/12777771/61711a15-5cff-4401-83b5-2224d5ebfb8b)

**Comment by anilbeesetti** [comment]
- I have implemented an option that allows the selection of external subtitles. 
- The issue of certain subtitles not loading, despite being associated with name of media file, stems from storage access problems specific to Android. NextPlayer, having media permissions, can only access media-related files by default. However, there appears to be a bug related to storage access, allowing some non-media files to be accessible as well. It's important to note that not all files can be accessed solely with media permissions.

**Comment by VasilisKos** [comment]
> * The issue of certain subtitles not loading, despite being associated with name of media file, stems from storage access problems specific to Android. NextPlayer, having media permissions, can only access media-related files by default. However, there appears to be a bug related to storage access, allowing some non-media files to be accessible as well. It's important to note that not all files can be accessed solely with media permissions.

But, as I said, subs can't be selected only when video file is opened through the file explorer. When opening through the Player file picker, they are always selectable and loaded.

**Comment by anilbeesetti** [comment]
That's fixed in #330. Checkout this debug build https://github.com/anilbeesetti/nextplayer/suites/13647191681/artifacts/753367716 which also includes experimental software video decoders

**Comment by anilbeesetti** [comment]
Let me know if the issue is still in that debug build

**Comment by VasilisKos** [comment]
> That's fixed in #330. Checkout this debug build https://github.com/anilbeesetti/nextplayer/suites/13647191681/artifacts/753367716 which also includes experimental software video decoders

The debug version has indeed solved the problem. Subs can be selected when video is opened through file explorer. Thanks! 
But there's another bug. When long tapping the subs button, to select external ones, the selected subs are not loaded automatically. You have to tap again the subs button to select them from the list, where they are added when selected. In fact everytime you select them they're added over and over again and in the subs list! Look at the screenshot I attach. 
And as kalekad has reported, long tapping the subs button would better open the video's folder by default.

![Screenshot_20230616-204333](https://github.com/anilbeesetti/nextplayer/assets/12777771/3e756764-6adf-43bf-b798-622a172ee7cd)

**Comment by anilbeesetti** [comment]
> 

I don't understand. Are they added over and over again when selecting subs in dialog or selecting from storage

**Comment by VasilisKos** [comment]
> > 
> 
> I don't understand. Are they added over and over again when selecting subs in dialog or selecting from storage

Every time they're selected from storage. Try selecting the same subs file from storage multiple times. Every single time the subs are added in the list.

**Comment by VasilisKos** [comment]
> That's fixed in #330. Checkout this debug build https://github.com/anilbeesetti/nextplayer/suites/13647191681/artifacts/753367716 which also includes experimental software video decoders

The debug version has a size issue. When installed it takes around 29 MB. After rebooting my device, it goes to 90+ MB! Is that normal? If that has to do with the software experimental codecs that were added, PLEASE leave them out in the next normal release! Keep it simple!
