### ISSUE TITLE
[Request] Subs encoding selection

### ISSUE THREAD

**Issue by VasilisKos** [anilbeesetti/nextplayer#316]
Please, add an option to select the subs file characters encoding. Some Greek subs for example are not displayed properly.

**Comment by DarremMolko** [comment]
I hope this is addressed in the next version because my Spanish subtitles (ISO-8859-1) are not displayed properly either.
![Screenshot_20230625-124306](https://github.com/anilbeesetti/nextplayer/assets/70179709/2e763a5e-22a7-4fa2-89c5-ad9016c886ce)

**Comment by VasilisKos** [comment]
> I hope this is addressed in the next version because my Spanish subtitles (ISO-8859-1) are not displayed property either. ![Screenshot_20230625-124306](https://user-images.githubusercontent.com/70179709/248836387-2e763a5e-22a7-4fa2-89c5-ad9016c886ce.png)

Try saving them in UTF-8 and it'll probably appear correctly.

**Comment by anilbeesetti** [comment]
@VasilisKos @DarremMolko Test this build and let me know:- https://github.com/anilbeesetti/nextplayer/suites/13885674256/artifacts/772125571

**Comment by DarremMolko** [comment]
@anilbeesetti it didn't fix it, at least for me. This is a screenshot from that build:
![Screenshot_20230627-102039](https://github.com/anilbeesetti/nextplayer/assets/70179709/711c19e0-0be8-4309-8010-9a030899dfc7)
I'm opening the video and subtitles through a document provider if that helps in any way.

**Comment by anilbeesetti** [comment]
@DarremMolko Can you share the subtitle file

**Comment by DarremMolko** [comment]
> @DarremMolko Can you share the subtitle file

Sure, here:
**REDACTED**

**Comment by VasilisKos** [comment]
> @VasilisKos @DarremMolko Test this build and let me know:- https://github.com/anilbeesetti/nextplayer/suites/13885674256/artifacts/772125571

Still a problem with ISO-8859-7. UTF appear normally.

**Comment by VasilisKos** [comment]
Here's the file in ISO-8859-7:
[Altered.Carbon.S01E01.Out.of.the.Past.720p.NF.WEB-DL.MkvCage.zip](https://github.com/anilbeesetti/nextplayer/files/11885379/Altered.Carbon.S01E01.Out.of.the.Past.720p.NF.WEB-DL.MkvCage.zip)

**Comment by anilbeesetti** [comment]
@VasilisKos @DarremMolko I've updated the build, I think it will work now. Build:- https://github.com/anilbeesetti/nextplayer/suites/13900987141/artifacts/773321209

**Comment by DarremMolko** [comment]
> @VasilisKos @DarremMolko I've updated the build, I think it will work now. Build:- https://github.com/anilbeesetti/nextplayer/suites/13900987141/artifacts/773321209

Yes, it seems to be fine now, my subtitles are displayed correctly:
![Screenshot_20230628-005710](https://github.com/anilbeesetti/nextplayer/assets/70179709/ec6fc947-14f8-4630-ba0e-97b3c69b7883)

**Comment by VasilisKos** [comment]
> @VasilisKos @DarremMolko I've updated the build, I think it will work now. Build:- https://github.com/anilbeesetti/nextplayer/suites/13900987141/artifacts/773321209

Yes! Works fine now!
P. S. The bold subs bug #388 is still present in this debug version.

**Comment by anilbeesetti** [comment]
@VasilisKos This bulid doesn't contain that patch. #388 patch is present in main branch

**Comment by anilbeesetti** [comment]
Hey @VasilisKos @DarremMolko In pull request #395 I've added a icu4 dependency to detect subtitle encoding. But it adds like 5-6mb size to the application. I searched for other solutions to detect encoding, but found none. Now is it ok if i just added a encoding selection setting or should i keep icu4j library. Let me know your thoughts on this

**Comment by VasilisKos** [comment]
> Hey @VasilisKos @DarremMolko In pull request #395 I've added a icu4 dependency to detect subtitle encoding. But it adds like 5-6mb size to the application. I searched for other solutions to detect encoding, but found none. Now is it ok if i just added a encoding selection setting or should i keep icu4j library. Let me know your thoughts on this

For me, definitely better add an encoding selection setting.

**Comment by DarremMolko** [comment]
> Hey @VasilisKos @DarremMolko In pull request #395 I've added a icu4 dependency to detect subtitle encoding. But it adds like 5-6mb size to the application. I searched for other solutions to detect encoding, but found none. Now is it ok if i just added a encoding selection setting or should i keep icu4j library. Let me know your thoughts on this

I'm fine with whatever option you choose, so go for it.

**Comment by anilbeesetti** [comment]
Great guys. Thank you

**Comment by VasilisKos** [comment]
I'm not sure whether this can be fixed, but the Auto option in the subs encoding setting doesn't recognize Greek ISO-8859-7 encoding. You have to select it manually in the setting. That's not much of a problem, but I mention it because other apps' "Auto" setting does recognize it. For example, Solid Explorer.
If it can't be resolved, keep this issue closed, but then what's the point of the "Auto" setting?

**Comment by anilbeesetti** [comment]
Auto is not implemented fully yet

**Comment by VasilisKos** [comment]
> Auto is not implemented fully yet

I guess "yet" means it's in the "todo" list? 😊

**Comment by anilbeesetti** [comment]
Yes, it's in the todo list. I need to find a way to detect character encoding without adding a massive external library

**Comment by bakinazik** [comment]
Any progress?
