### ISSUE TITLE
App is incompatible with android 6

### ISSUE THREAD

**Issue by ghost** [anilbeesetti/nextplayer#324]
Please support android 6

**Comment by Justauser0** [comment]
Any update

**Comment by ghost** [comment]
Any update

**Comment by anilbeesetti** [comment]
I haven't checked yet. Will check soon

**Comment by ghost** [comment]
> I haven't checked yet. Will check soon

Good. Because there is no good video player except MX player (Not open source) and VLC (Quite annoying)

**Comment by anilbeesetti** [comment]
- implemented in #407
