### ISSUE TITLE
[Feature Request] Add long press gesture（添加长按手势）

### ISSUE THREAD

**Issue by ygxbnet** [anilbeesetti/nextplayer#345]
# Could add a long press gesture?

Specific instructions: 

- Long press and hold the screen to play the video in multiple.
- Release your hand and stop playing in multiple.

I think this feature can be included as an optional option in the settings, which is very useful and can optimize the experience of playing videos

I hope you can accept this proposal. Thank you

---

**Example:**

https://github.com/anilbeesetti/nextplayer/assets/87907576/ae9982d1-f41c-46c3-b087-17796af872b2

**Comment by Yashraj254** [comment]
@anilbeesetti can i work on this feature?

**Comment by ygxbnet** [comment]
@anilbeesetti Hello, This issue has been opened by me for 3 months, and the function has been implemented in #486  , but it has not been merged. I hope it can be merged soon.

Thanks again for this project

**Comment by anilbeesetti** [comment]
@ygxbnet I will merge this once all merge conflicts are resolved

**Comment by ygxbnet** [comment]
I'd be happy to help you with conflict resolution in #486 , but I don't know what to do

so what should i do?

**Comment by ygxbnet** [comment]
@anilbeesetti @Yashraj254 Thank you very much for adding this feature, which will make me more like this software
