### ISSUE TITLE
Option to disable Black background behind the Subtitles 

### ISSUE THREAD

**Issue by rebelutioner** [anilbeesetti/nextplayer#351]
It should be transparent as the black background is non intensive and hinders with an immersive experience.

**Comment by Pentaphon** [comment]
Yes, we need subtitle settings because the current subs do not honor the caption settings.

**Comment by VasilisKos** [comment]
Enable subs in Android settings, and choose their style there. That's what Next Player follows. No need for further settings.

**Comment by rebelutioner** [comment]
I don't intend to enable it system wide just for a specific app, it's normal behavior to be persistent within the app itself especially if it's a media player not everyone will turn on system wide caption settings. Just doesn't makes sense.
