### ISSUE TITLE
Background audio playback and lockscreen controls

### ISSUE THREAD

**Issue by Lorestan00** [anilbeesetti/nextplayer#359]
It would be great to have two features - background audio playback and lockscreen media controls like mx player

**Comment by VasilisKos** [comment]
Go install MX Player! Why do you all users ask for more and more MX Player and VLC features? The difference of Next Player is that it's supposed to be a simple and clean of useless features and settings VIDEO player! NOT a music player! And that's how it should be kept!

**Comment by Lorestan00** [comment]
Well the reason why 'all users' are asking for these features from MX player is that they are important to them. The reason they aren't using MX Player is that it doesn't give them everything they want...perhaps abit bloated too many unnecessary features...thats the case for me. Hope thats clear!

Users generally will compare apps to other apps especially with early releases. Pretty normal behaviour

**Comment by nyas1** [comment]
> Go install MX Player! Why do you all users ask for more and more MX Player and VLC features? The difference of Next Player is that it's supposed to be a simple and clean of useless features and settings VIDEO player! NOT a music player! And that's how it should be kept!

dude is pasting same comment everywhere

**Comment by Lorestan00** [comment]
Why is he so angry? No need

**Comment by ghost** [comment]
Any update

**Comment by serrq** [comment]
Playing a video as an audio track in background. Thumb up.

**Comment by Pentaphon** [comment]
Duplicate of https://github.com/anilbeesetti/nextplayer/issues/251

**Comment by anilbeesetti** [comment]
- Done in #1103
