### ISSUE TITLE
[Feature Request] Add audio section like VLC media player

### ISSUE THREAD

**Issue by laraib07** [anilbeesetti/nextplayer#361]
The app is fantastic. It plays video more smoothly than VLC (at least in my use case). I would love to replace VLC with Next Player in future. 

Kindly, add more useful features and a better UI/UX. Copying successful apps like VLC, MX player, Netflix, etc wouldn't hurt.

**Comment by VasilisKos** [comment]
No. Copying apps like VLC and MX WOULD hurt. This app is really awesome because it doesn't copy any other, and it's supposed to be a simple and minimal VIDEO player. If someone wants something else, there are plenty of other choices out there. No need to spoil this app.

**Comment by laraib07** [comment]
@VasilisKos With due respect, I disagree. There are plenty of simple and minimal open-source video players, such as Just Player, MPV, and YetAnotherVideoPlayer. However, there are only a few fully-featured ones like VLC.

**Comment by VasilisKos** [comment]
> @VasilisKos With due respect, I disagree. There are plenty of simple and minimal open-source video players, such as Just Player, MPV, and YetAnotherVideoPlayer. However, there are only a few fully-featured ones like VLC.

I disagree my friend. Just and Next are the only open source, minimal, Exoplayer based ones. I moved from Just to Next, because it's much lighter, and Just had some unsolved bugs. 
Anyway, all users can express their opinions, and the last word belongs to the dev himself.

**Comment by anilbeesetti** [comment]
currently the app is only for video playback

**Comment by VasilisKos** [comment]
> currently the app is only for video playback

I hope "currently" refers to "forever".😁
