### ISSUE TITLE
Light splash screen

### ISSUE THREAD

**Issue by kalekad** [anilbeesetti/nextplayer#366]
app debug build and v0.2.0 release
LineageOS 20 (Android 13)
Samsung

Despite having the dark theme enabled in app and dark mode enabled on my phone, the splash screen is always light.
![Screenshot Next Player Debug](https://github.com/anilbeesetti/nextplayer/assets/73171174/c02a4fd1-b52d-45bb-989f-08b2569ed466)

**Comment by VasilisKos** [comment]
What splash screen? Is there a splash screen at all? 😳

**Comment by exolon** [comment]
I've never noticed a splash screen in this app... A13 and 14 here

**Comment by Yashraj254** [comment]
@anilbeesetti can i work on this issue, also i have thought of using md_theme_dark_background color for splash screen background color.

**Comment by anilbeesetti** [comment]
Hey @Yashraj254, I am already working on that check splash screen branch. if you think you got something better then let me know

**Comment by Yashraj254** [comment]
@anilbeesetti that looks good..
