### ISSUE TITLE
Screen rotation icon

### ISSUE THREAD

**Issue by kalekad** [anilbeesetti/nextplayer#367]
app debug build
LineageOS 20 (Android 13)
Samsung

The screen rotation icon is different the first time than it is after changing to the same position.

1.
![1Screenshot Next Player Debug](https://github.com/anilbeesetti/nextplayer/assets/73171174/b5d38659-b3e6-4a56-a372-05a2ab1aadf2)

2.
![2Screenshot Next Player Debug](https://github.com/anilbeesetti/nextplayer/assets/73171174/6fa26373-1515-45e3-9f4e-7f00fbc33ec4)

---------------------------

As VasilisKos mentions below, this is not a bug of not returning the same icon in the same state.

The problem is that the manual/auto/etc rotation icon does not match the current state.

For example, the auto rotation icon is displayed even if auto rotation is not possible(auto rotation disabled in the system).

**Comment by VasilisKos** [comment]
This is not a bug. The first icon appears when auto rotation is enabled. If you tap it, then you turn it to fixed rotation, which is the second icon. Every time you tap that button, it rotates the screen. Long tapping it turns it back to auto, and the respective first icon is back. 😉

**Comment by kalekad** [comment]
Oh, I see. I'm updating the bug report. Thanks for the hint.
