### ISSUE TITLE
Feature Request (D2TF 10Sec)

### ISSUE THREAD

**Issue by Sureshgorai25** [anilbeesetti/nextplayer#379]
Double tap to forward only 10 seconds feature.
I know we have an option of choosing how much we want to forward by double tapping, but it would be great ig you add 10 seconds, instead of decide itself or to the next chapter.

**Comment by mehedi-codes** [comment]
it would be nice to have this feature.

**Comment by mehedi-codes** [comment]
Libretube has this feature with a simple animation something like that would be great.

**Comment by anilbeesetti** [comment]
- implemented in #424
