### ISSUE TITLE
[BUG] Subs font appearing bold on every initial app launch 

### ISSUE THREAD

**Issue by VasilisKos** [anilbeesetti/nextplayer#388]
When the bold subs font is disabled in the settings, the first time the app is launched and a video is started, the subs appear as bold. Stopping and restarting the video shows the subs normaly (not bold).

**Expected behavior**
The subs should never be bold, when chosen so in the settings.

**Device info (please complete the following information):**
 - Device: Nokia 6.2
 - Android version: 11
 - App version: 0.3.0

**Comment by anilbeesetti** [comment]
I checked and will release a hot fix for this soon

**Comment by VasilisKos** [comment]
> I checked and will release a hot fix for this soon

Thanks. Please implement the updated translations. The subs settings translation hasn't been added. 😉

**Comment by anilbeesetti** [comment]
- Related to #392
