### ISSUE TITLE
[Feature Request] More quick settings options

### ISSUE THREAD

**Issue by Maha-Rajan** [anilbeesetti/nextplayer#389]
Currently the Quick Setting is utilised minimally with good UI/UX experience but I feel the functionality could be extended a bit more without loosing it's UI/UX... 

I've been using MX player for a long time and I've finally switched to Next player. There are many things Next player could borrow from MX player imo.. I'll point out to the Quick Setting dialogue box... There is an option called fields in the QS dialogue box in MX player that allows to specify what information should be displayed along with the name and thumbnail. This is fairly a simple yet good user functionality that can be implemented. Ex.. I might want to see the frame rate and may be not see the path location... I'll attach a screenshot 
![Screenshot_20230626-180627](https://github.com/anilbeesetti/nextplayer/assets/40870763/783d1595-484a-44dc-9d9f-8f66f58a5683)
for you to look in to it..

**Comment by MrDark-code** [comment]
I think you can also add color format selection like in MX Player, since I noticed that rgb-16-bit works by default for software decoders
![Screenshot_2023-07-24-21-41-09-076_com mxtech videoplayer pro](https://github.com/anilbeesetti/nextplayer/assets/137885849/36d39a46-9171-4ec5-a6b2-73ea25ebc8d4)

**Comment by anilbeesetti** [comment]
@MrDark-code what's the use of the color format setting. Is something not working as it should

**Comment by MrDark-code** [comment]
> @anilbeesetti 

Mx  Player yuv or 32 bit sw
![Screenshot_2023-07-24-12-31-55-311_com mxtech videoplayer pro](https://github.com/anilbeesetti/nextplayer/assets/137885849/148b86b5-7099-45aa-a40a-0913a39bfa92)
Next 16 bit sw
![Screenshot_2023-07-24-12-33-07-011_dev anilbeesetti nextplayer](https://github.com/anilbeesetti/nextplayer/assets/137885849/685d3b7e-6b82-470e-ad76-1c0a1945f447)
Mx Player 16 bit sw
![Screenshot_2023-07-24-17-37-26-335_com mxtech videoplayer pro](https://github.com/anilbeesetti/nextplayer/assets/137885849/19973d8b-3fcd-486f-b4d9-9af6ffe68480)

**Comment by anilbeesetti** [comment]
I don't understand, they all look similar to me. Am i missing something

**Comment by MrDark-code** [comment]
> @anilbeesetti 
hue colors are slightly different 😉
try to run it on two players (mx sw and next sw) and change the color format, so it's better to notice.

**Comment by anilbeesetti** [comment]
I don't know how mx player implements it. But next player converts all color formats to yuv and renderes it on screen

**Comment by MrDark-code** [comment]
@anilbeesetti 
earlier on android, a similar technology was still on VLC
