### ISSUE TITLE
Icon submission 

### ISSUE THREAD

**Issue by Maha-Rajan** [anilbeesetti/nextplayer#390]
I've tried to use to current color palette and shape..
<img width="501" alt="Asset 9@2x" src="https://github.com/anilbeesetti/nextplayer/assets/40870763/27a77bc6-8652-4ea9-b6b5-1ac7211542b9">
<img width="501" alt="Asset 8@2x" src="https://github.com/anilbeesetti/nextplayer/assets/40870763/24ed6939-2138-43f8-8974-299cc57fc735">

Let me what you think about it... I'll be happy to fine tune it if you have some other better idea

**Comment by VasilisKos** [comment]
The 1st one is really nice!

**Comment by anilbeesetti** [comment]
Could you please create a new discussion for this
