### ISSUE TITLE
[BUG] Default preferences are used in player on initial app launch

### ISSUE THREAD

**Issue by anilbeesetti** [anilbeesetti/nextplayer#392]
**Describe the bug**
Updated preferences not used in player activity on initial app launch

**To Reproduce**
1. Open app
2. Go to Player settings or subtitle settings
3. Modify settings
4. Close app from background
5. Open app and play some video

**Expected behavior**
Player to use updated preferences

**Actual behavior**
Player using default preferences set by app

**Application Version**
v0.3.0

**Comment by Sureshgorai25** [comment]
Subtitles rn't working for me too

**Comment by anilbeesetti** [comment]
> Subtitles rn't working for me too

Could you provide more context please

**Comment by Sureshgorai25** [comment]
> > Subtitles rn't working for me too
> 
> Could you provide more context please

My default subtitles language is set to English and the other settings are unchanged but when I play a video, which has subtitles on it, it doesn't shows the subtitles even though I tapped on the subtitle/caption and tried several times.

**Comment by anilbeesetti** [comment]
@Sureshgorai25 Does this happen for one video or all videos. Providing a sample video would be great

**Comment by Sureshgorai25** [comment]
It's not working for some videos

**Comment by anilbeesetti** [comment]
Then I need a sample video to test

**Comment by anilbeesetti** [comment]
@Sureshgorai25 Are subtitles external files or embedded into video

**Comment by anilbeesetti** [comment]
fixed in #393
