### ISSUE TITLE
[Feature Request] Add a setting to not save videos positions

### ISSUE THREAD

**Issue by Darkishe** [anilbeesetti/nextplayer#402]
Thanks for the app, I like it a lot and it'd be perfect if you could add the possibility to not remember the positions of the videos. Even if you delete the video, if you download it back when you play it it'll remember the position.

**Comment by anilbeesetti** [comment]
Open settings -> player -> resume -> no

**Comment by Darkishe** [comment]
> Open settings -> player -> resume -> no

Oh sorry I didn't see it, my bad.
