### ISSUE TITLE
[BUG] Subtitles settings are not working

### ISSUE THREAD

**Issue by Darkishe** [anilbeesetti/nextplayer#408]
If you try the different options for subtitles, only the "subtitle background" option is working.

**Comment by anilbeesetti** [comment]
What is the subtitle type? Provide me a screen recording of settings and player subtitles if possible

**Comment by Darkishe** [comment]
> What is the subtitle type? Provide me a screen recording of settings and player subtitles if possible

It's .ass subtitles and here's a screen recording https://streamable.com/kd162l

**Comment by anilbeesetti** [comment]
@jojobozo i see that .ass subtitles doesn't use app subtitle settings. I will add an option to force these settings even for ass subtitles

**Comment by Darkishe** [comment]
> @jojobozo i see that .ass subtitles doesn't use app subtitle settings. I will add an option to force these settings even for ass subtitles

Thanks!
