### ISSUE TITLE
Improvement request: remember subtitle status when reopening file

### ISSUE THREAD

**Issue by exolon** [anilbeesetti/nextplayer#434]
Right now if I stop a video with subs enabled and continue the next day, I must enable subs again... Also maybe an option for vids always starting having subs on?

**Comment by anilbeesetti** [comment]
Are you taking about external subs opened by long pressing subtitle icon or subtitles included in the video?

**Comment by exolon** [comment]
Ah hadn't noticed but I just checked, internal subs work as described so I guess it was about external ones...

**Comment by anilbeesetti** [comment]
Great. I'll fix this in next release

**Comment by exolon** [comment]
Great!

**Comment by anilbeesetti** [comment]
@exolon Could you check if the issue is resolved in the latest release and if so close the issue otherwise let me know

**Comment by exolon** [comment]
Yup, it works :) Thanks!!
