### ISSUE TITLE
Add option to skip multiple second 

### ISSUE THREAD

**Issue by ghost** [anilbeesetti/nextplayer#440]
Add option to skip multiple second  like this 
![20230717_132238](https://github.com/anilbeesetti/nextplayer/assets/135147872/27fcca9e-40b1-4a71-884b-112ab1af1907)

**Comment by ghost** [comment]
It would be great feature

**Comment by ghost** [comment]
> I think this function is in Settings->Player->Double tap->Fast forward/Rewind+Seek increment+Seek gesture

You are talking about completely different thing

**Comment by anilbeesetti** [comment]
> I think this function is in Settings->Player->Double tap->Fast forward/Rewind+Seek increment+Seek gesture

This works fine. No need to add another way to skip
