### ISSUE TITLE
(DOUBT) Can we publish this app in  Play Store

### ISSUE THREAD

**Issue by gnanesh023** [anilbeesetti/nextplayer#453]
Can I publish this app in the play store with some modification 
is there any policy violations there?

**Comment by anilbeesetti** [comment]
No you can't publish this app. I'm planning on publishing it to playstore myself

**Comment by VasilisKos** [comment]
> No you can't publish this app. I'm planning on publishing it to playstore myself

Better not as an early access. #323

**Comment by markg85** [comment]
So... Technically (license wise) nothing prohibits @gnanesh023 to make a fork and publish it on the play store. That's all perfectly legal and fine. It does show the downside of open source and permissive licenses in this specific case.

Morally though. It would be a dick move to go against the author of the project you're forking.

**Comment by VasilisKos** [comment]
> So... Technically (license wise) nothing prohibits @gnanesh023 to make a fork and publish it on the play store. That's all perfectly legal and fine. It does show the downside of open source and permissive licenses in this specific case.
> 
> Morally though. It would be a dick move to go against the author of the project you're forking.

Yeah. Play is full of such dicks... Some of them even upload such forks as non-free apps!
