### ISSUE TITLE
[BUG] Crash on changing the default playback speed preference slider

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [anilbeesetti/nextplayer#459]
## Describe the bug ##
If I want to move the default playback speed (see screenshot) to the left or right, the app quits.

## Device info ##
 - Device: [Samsung S21 5G]
 - Android version: [13]
 - App version: [0.4.0]

## Conclusion ##
The app itself is cool, I use it every day.

![nextplayerbug](https://github.com/anilbeesetti/nextplayer/assets/61406324/fb891b52-007a-4ccd-a38d-ab27ba836502)

**Comment by anilbeesetti** [comment]
It's working fine on my phone. Maybe try uninstalling and reinstalling the app and let me know if the issue still persists

**Comment by mondlicht-und-sterne** [comment]
i do it but is the same problem

**Comment by anilbeesetti** [comment]
can you please share a screen recording, it will be helpful

**Comment by VasilisKos** [comment]
> can you please share a screen recording, it will be helpful

The bug is present in my phone with version 0.6.0. Also, the app crashes when moving the speed slider when playing videos. I've sent for both crash reports through Play.

**Comment by anilbeesetti** [comment]
@VasilisKos maybe a clean install can solve this. Let me know if that helps

**Comment by VasilisKos** [comment]
> @VasilisKos maybe a clean install can solve this. Let me know if that helps

No, that didn't help...
P.S. The crash happens also when tapping the +- buttons in the slider window.
P.S.2 Using a Nokia 6.2 with Android 11.
P.S. For some reason, after deleting all data, uninstallling and reinstalling the app, the settings were restored to the ones I had set before. Like not all data were deleted. Have you enabled Google backup for the app or something?

**Comment by anilbeesetti** [comment]
@VasilisKos No, it should delete all app data

**Comment by VasilisKos** [comment]
> @VasilisKos No, it should delete all app data

I uninstalled the Play version, and installed the GitHub one. Settings were the default ones, not the ones I had set before. The bug is present in that version too.
After uninstalling the GitHub version, and installing the Play one, the settings were restored to the ones I had set before. :P 
I guess the settings are indeed saved in the cloud by Google...

**Comment by anilbeesetti** [comment]
@VasilisKos I'm not seeing this error in my phones or not in any emulators. Can you try this the debug version https://github.com/anilbeesetti/nextplayer/suites/14937693719/artifacts/851598362 and if you can please share the error log

**Comment by VasilisKos** [comment]
> @VasilisKos I'm not seeing this error in my phones or not in any emulators. Can you try this the debug version https://github.com/anilbeesetti/nextplayer/suites/14937693719/artifacts/851598362 and if you can please share the error log

I don't see any error log. Is it stored somewhere?

**Comment by anilbeesetti** [comment]
No, it's not stored in any location. You must retrieve it through logcat. I'm aware that obtaining logs from logcat might not be practical for the majority, so proceed only if you're able to do so.

**Comment by VasilisKos** [comment]
> No, it's not stored in any location. You must retrieve it through logcat. I'm aware that obtaining logs from logcat might not be practical for the majority, so proceed only if you're able to do so.

I see. As I said before, I've send a couple of reports through Android after the crashes. Don't they reach you in some way? Those should be helpful.

**Comment by anilbeesetti** [comment]
I think they will some time later, i don't know for sure. This is my app in google play

**Comment by VasilisKos** [comment]
I've tested all the app versions since 0.3.0, when the speed slider was added. The bug is present in all versions after that. Not when changing the speed through the bullet menu. Only with the slider. Both in the settings, and the popup window in the player.
Sorry for not testing before.

P.S. For me the speed selection feature is pretty much useless, but anyway...

**Comment by anilbeesetti** [comment]
I don't understand, why this bug only seen in some selected phone. I will have to investigate more on this

**Comment by VasilisKos** [comment]
> I don't understand, why this bug only seen in some selected phone. I will have to investigate more on this

Just tested Play version on a Xiaomi Redmi 9C. Bug is present.
I think it happens on most (if not all) devices. It's just that most users probably don't use the playback speed feature, like me, so they haven't noticed the bug...

**Comment by DarremMolko** [comment]
Regarding the settings being saved in the Google Play version, this may be because it has  "allowbackup" set to true in the app manifest:
![Screenshot_20230812-163425](https://github.com/anilbeesetti/nextplayer/assets/70179709/c9cc35b5-2be6-435e-b35c-c2794b713016)
More info here:
https://developer.android.com/guide/topics/data/autobackup#EnablingAutoBackup

**Comment by VasilisKos** [comment]
> Regarding the settings being saved in the Google Play version, this may be because it has "allowbackup" set to true in the app manifest: ![Screenshot_20230812-163425](https://user-images.githubusercontent.com/70179709/260255928-c9cc35b5-2be6-435e-b35c-c2794b713016.png) More info here: https://developer.android.com/guide/topics/data/autobackup#EnablingAutoBackup

Thanks. I like this feature. I hope the dev doesn't change it.

**Comment by DarremMolko** [comment]
> > Regarding the settings being saved in the Google Play version, this may be because it has "allowbackup" set to true in the app manifest: ![Screenshot_20230812-163425](https://user-images.githubusercontent.com/70179709/260255928-c9cc35b5-2be6-435e-b35c-c2794b713016.png) More info here: https://developer.android.com/guide/topics/data/autobackup#EnablingAutoBackup
> 
> Thanks. I like this feature. I hope the dev doesn't change it.

It's a nice feature but it has its downsides, it breaks sometimes when migrating from one android version to another. I think it's safer to be able to manually backup the settings.

**Comment by Denio-7** [comment]
RedMi Note 7 Pro
Android 10
NextPlayer 0.6.0 Github

Bug confirmed.

(Nice app, thanks for Your work, following).

**Comment by anilbeesetti** [comment]
Can someone share a screen recording

**Comment by Denio-7** [comment]
> Can someone share a screen recording

Sure: https://cloud.mail.ru/public/zGTg/vtmfShekG

**Comment by anilbeesetti** [comment]
Check official issue on Material components for more info on this issue:  https://github.com/material-components/material-components-android/issues/1290

**Comment by anilbeesetti** [comment]
Hey  guys, I tried something to fix the issue. Try this build and let me know. https://github.com/anilbeesetti/nextplayer/suites/15214281808/artifacts/869449527

**Comment by VasilisKos** [comment]
> Hey guys, I tried something to fix the issue. Try this build and let me know. https://github.com/anilbeesetti/nextplayer/suites/15214281808/artifacts/869449527

The slider works fine when playing a video. But the app still crashes when moving the slider in the settings. 🤪
I think you're close to fixing this! 😁

**Comment by anilbeesetti** [comment]
i only changed the slider in player for now. If this build fixes that issue then i will proceed and fix the slider in settings too

**Comment by Denio-7** [comment]
> Hey guys, I tried something to fix the issue. Try this build and let me know. https://github.com/anilbeesetti/nextplayer/suites/15214281808/artifacts/869449527

Yep, everything is cool. Works correctly, slider & buttons too.

**Comment by anilbeesetti** [comment]
Hello @VasilisKos, Checkout this build and let me know if sliders in player and preferences are still crashing or not. https://github.com/anilbeesetti/nextplayer/suites/15252381725/artifacts/871477810

**Comment by VasilisKos** [comment]
> Hello @VasilisKos, Checkout this build and let me know if sliders in player and preferences are still crashing or not. https://github.com/anilbeesetti/nextplayer/suites/15252381725/artifacts/871477810

👏👍 Bingo! Works fine! I was sure you would make it! Good job! 😉

**Comment by mondlicht-und-sterne** [comment]
Yes it works ❤️
