### ISSUE TITLE
[BUG] need feature for movie info fetch & group video by folder by folder like in mxplayer

### ISSUE THREAD

**Issue by VigneshwarAshokan** [anilbeesetti/nextplayer#463]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device info (please complete the following information):**
 - Device: [e.g. Google Pixel 3]
 - Android version: [e.g. 12]
 - App version: [e.g. v0.1.1 (2)]

**Additional context**

**Comment by anilbeesetti** [comment]
Movie info fetching is not planned and group video by folder by folder is tracked at #290
