### ISSUE TITLE
[FEATURE] Picture in Picture (pip) support

### ISSUE THREAD

**Issue by socksprox** [anilbeesetti/nextplayer#471]
**Describe the feature**
If I leave the player with a video playing, a small window opens with the video  so it can be continued watching. Otherwise, there should be a small button I can press to open it in Picture in Picture too

**Device info (please complete the following information):**
 - Device: Xiaomi 12T Pro
 - Android version: 13 (Xiaomi.eu custom Rom)
 - App version: 0.5.0 (fdroid)

**Additional context**
Add feature request as GitHub template

**Comment by VasilisKos** [comment]
Would you be kind enough to read the description in the GitHub page BEFORE posting an issue?
"Planned features: picture in picture"!

**Comment by socksprox** [comment]
Sorry, you’re right.

**Comment by Pentaphon** [comment]
Dupe of https://github.com/anilbeesetti/nextplayer/issues/250

**Comment by walrus543** [comment]
@PalmTamino please close this issue.
