### ISSUE TITLE
Offline version

### ISSUE THREAD

**Issue by lokomoto** [anilbeesetti/nextplayer#487]
Would you consider providing an offline version of the app, without internet permission?

I think it's generally a good practice to separate the apps with storage access from the ones with internet access.
Currently it's possible to use the app for network streams without granting storage permission #418, but the opposite isn't, due to AOSP permission management limitations.

**Comment by Gamer750** [comment]
> Would you consider providing an offline version of the app, without internet permission?
> 
> I think it's generally a good practice to separate the apps with storage access from the ones with internet access. Currently it's possible to use the app for network streams without granting storage permission #418, but the opposite isn't, due to AOSP permission management limitations.

I agree but it would be more like a gallery

**Comment by anilbeesetti** [comment]
Not planned now and never will be
