### ISSUE TITLE
Can't play libretube videos on nextplayer

### ISSUE THREAD

**Issue by Gamer750** [anilbeesetti/nextplayer#490]
Can't play libretube videos on nextplayer.But some video players support

**Comment by anilbeesetti** [comment]
@Gamer750 What other video players support libretube videos?

**Comment by Gamer750** [comment]
> @Gamer750 What other video players support libretube videos?

VLC video player

**Comment by anilbeesetti** [comment]
Are you saying vlc can play videos after downloaded from libretube or with video link?

**Comment by Gamer750** [comment]
With link

**Comment by anilbeesetti** [comment]
It's not working for me with vlc. Can you share a screen recording.

**Comment by Gamer750** [comment]
Long press the share button then the list of video players will be shown

**Comment by Gamer750** [comment]
https://github.com/anilbeesetti/nextplayer/assets/141329708/fcd56277-abfa-4311-a092-3fa3d82994fb

**Comment by anilbeesetti** [comment]
@Gamer750 got it. I'll work on this soon

**Comment by Gamer750** [comment]
OK
