### ISSUE TITLE
how to add music folder?

### ISSUE THREAD

**Issue by wx69wx** [anilbeesetti/nextplayer#499]
the app only support video folder added?  how to add music folder? thanks a lot!

**Comment by VasilisKos** [comment]
"Next Player is an Android native **VIDEO** player"

**Comment by Pentaphon** [comment]
Dude, use a music player.

**Comment by wx69wx** [comment]
thanks，but it really can play music，so I  don't want to install another
music app.

**Comment by Pentaphon** [comment]
> thanks，but it really can play music，so I don't want to install another
music app.

That's up to the Nextplayer dev, not you. This is a video player.

**Comment by anilbeesetti** [comment]
@wx69wx This is a video player only, so you can't add music folder
