### ISSUE TITLE
[Feature]: Add Fast forward during silence option

### ISSUE THREAD

**Issue by brnwlshubh** [anilbeesetti/nextplayer#517]
Please Add a feature of Fast forward during silence

**Comment by drogga** [comment]
Probably the same as #345, there's also a PR for this, which I'm hoping to be merged ASAP, but I don't know why this suggestion is disliked 3 times already, it's a nice and useful feature...

**Comment by xd003** [comment]
> Probably the same as #345, there's also a PR for this, which I'm hoping to be merged ASAP, but I don't know why this suggestion is disliked 3 times already, it's a nice and useful feature...

I don't get how is this request same as the feature request you have linked. That one is simply increasing the speed of the video being played on gestures like long press. Agreed its very useful and not really much complex to implement as well

Tbh i can't quite understand what this particular feature request is even for, its very unclear. I don't know what "Fast Forwarding during silence" is supposed to mean

**Comment by brnwlshubh** [comment]
> Tbh i can't quite understand what this particular feature request is even for, its very unclear. I don't know what "Fast Forwarding during silence" is supposed to mean

To experience this feature you have to use NewPipe

**Comment by drogga** [comment]
https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/audio/SilenceSkippingAudioProcessor.java

**Comment by Noitarud** [comment]
You can also use [Just (Video) Player (issue link given)](https://github.com/moneytoo/Player/issues/307#issuecomment-1741854737), it is disableable.
I had one issue with their implementation though, if I was listening to a lecture, some pause or partial slowdown is necessary else the facts get said too quick - but author will not offer speeds other than Exoplayer defaults and recommends Next Player.

**Comment by ildar** [comment]
> https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/audio/SilenceSkippingAudioProcessor.java

ExoPlayer already has it implemented. Why not just propagate it to the UI?

**Comment by PacoBell** [comment]
So close, yet so far. I absolutely love Just (Video) Player's implementation of this, but they don't support any playback speeds >2X. Meanwhile, Next Player supports plenty of playback speeds, yet is missing silence skipping. If only someone could crib code from both projects and create the perfect video player 😭

Edit: After going through Just Player's source, it's just as simple as setting player.setSkipSilenceEnabled(true) in AudioAttributes.Builder().

**Comment by brnwlshubh** [comment]
@anilbeesetti 

Can You enable an option to Remember the option for this feature.
