### ISSUE TITLE
[BUG] White/Bright screen every time the app launch

### ISSUE THREAD

**Issue by JFMugen** [anilbeesetti/nextplayer#535]
**Describe the bug**
Whenever you start the app it launches with a bright white screen for half second, which makes it hard to use it as a default video player, especially at night. 

**To Reproduce**
Just open a video from gallery with Next Player

**Expected behavior**
Either 
A) Black screen
B) Just delay opening the app (if possible)

**Screenshots**
I can add recording if needed

**Device info (please complete the following information):**
 - Device: Huawei P9 Lite 2017
 - Android version: 8
 - App version: 0.7.0

**Comment by anilbeesetti** [comment]
@JFMugen Thanks for reporting this. I've added a fix for this and it will be available in the next release

**Comment by drogga** [comment]
There's still a full white screen even with the `high contrast dark` (amoled), in fact the appearance preferences don't make any difference to this.
The `Just Player` app (by moneytoo) doesn't show  a white screen while launching from the app shortcut _(from the app drawer or a home screen one - which ofc. doesn't matter)_
Both on Lineage 18.1 (A.11) on a pretty old and low-end device.

At this point I'm used to seeing those, so they don't bother me that much anymore, so I'm just pointing it out, tho it will be better ofc. if it doesn't appear, but IDK if there's something to be "fixed" regarding this, or if it can be at all...

**Comment by anilbeesetti** [comment]
The PR #537 fixes white screen when launching video from gallery or file manager only. I know about the white screen on app launch from app drawer and will fix it in next release

**Comment by JFMugen** [comment]
@anilbeesetti it indeed fixed the white screen when launching from gallery or file manager etc, awesome ^^ 

(but this version made the app like x100 heavier for some reason, I can't even change theme without the app freezing for 10 seconds, this is a known thing?)

**Comment by anilbeesetti** [comment]
@JFMugen that is reported by you only. @VasilisKos do you see any freezing with the app in the new release

**Comment by VasilisKos** [comment]
> @JFMugen that is reported by you only. @VasilisKos do you see any freezing with the app in the new release

No. Works fine.

**Comment by anilbeesetti** [comment]
@VasilisKos Thank you. And @JFMugen Could you try this debug build and let me know if this freezes also: https://github.com/anilbeesetti/nextplayer/suites/15917785164/artifacts/908559254

**Comment by JFMugen** [comment]
Alright, I just reinstalled and looks normal right now. Maybe something happened while updating :/

**Comment by JFMugen** [comment]
> https://github.com/anilbeesetti/nextplayer/suites/15917785164/artifacts/908559254

Just saw that, you still want me to try it?

**Comment by anilbeesetti** [comment]
> Alright, I just reinstalled and looks normal right now. Maybe something happened while updating :/

@JFMugen If it freezes again let me know. I'll try to fix that

**Comment by anilbeesetti** [comment]
> > https://github.com/anilbeesetti/nextplayer/suites/15917785164/artifacts/908559254
> 
> Just saw that, you still want me to try it?

you can try if you want to. This is debug build and it will be slow

**Comment by JFMugen** [comment]
@anilbeesetti Well, everything looks normal now. Thanks for the replies :)
