### ISSUE TITLE
[BUG] the high contrast is on and can not be turned of even if you turn the toggle of

### ISSUE THREAD

**Issue by Skullhunter11** [anilbeesetti/nextplayer#571]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device info (please complete the following information):**
 - Device: [e.g. Google Pixel 3]
 - Android version: [e.g. 12]
 - App version: [e.g. v0.1.1 (2)]

**Additional context**

**Comment by anilbeesetti** [comment]
@Skullhunter11 Can you share a screen recording if possible

**Comment by Skullhunter11** [comment]
https://github.com/anilbeesetti/nextplayer/assets/104146790/6928f258-1fcb-4fc1-8ddc-5f2e42193e0a

**Comment by anilbeesetti** [comment]
@Skullhunter11 what's background color in previous version using dynamic theming

**Comment by Skullhunter11** [comment]
This color
#1F1A1E

**Comment by anilbeesetti** [comment]
Edited: I was wrong, It will be fixed in pr #574 and will release a hotfix release soon
