### ISSUE TITLE
PiP (Picture in Picture) Mode 

### ISSUE THREAD

**Issue by Skullhunter11** [anilbeesetti/nextplayer#573]
For when people like me want to watch a video while scrolling

**Comment by VasilisKos** [comment]
Please, READ THE DESCRIPTION before posting:

"Planned Features:
External Audio support
**Picture-in-picture mode**"

**Comment by Pentaphon** [comment]
Dupe of https://github.com/anilbeesetti/nextplayer/issues/250

**Comment by walrus543** [comment]
@Skullhunter11 please close this issue.

**Comment by anilbeesetti** [comment]
- feature added in PR #646
