### ISSUE TITLE
Feature: close on end or loop

### ISSUE THREAD

**Issue by Turhvjbufv** [anilbeesetti/nextplayer#592]
Currently if "autoplay" is off, when the video ends it just stays there and does nothing
Suggestion: add an option that instead of "autoplay" we could also choose "loop"(that would infinitely loop the current video that we are watching)(maybe even add that on the player screen so we easily turn it on/off).
and another option that we could "close player" (closes next player when the video ends).
Thank you.

**Comment by anilbeesetti** [comment]
Now it closes player after video ends
