### ISSUE TITLE
Long time to respond

### ISSUE THREAD

**Issue by obaidabit** [anilbeesetti/nextplayer#593]
**Describe the bug**
The app is too slow after the 0.8 update, the app takes a long time to respond to any action.
after a couple of minutes, the app just crashes.

**To Reproduce**
Install the v0.8 update, and open the app for the second time.

**Expected behavior**
Normal performance

**Screenshots**

**Device info (please complete the following information):**
 - Device: Samsung Galaxy A8 2017
 - Android version: 9
 - App version: 0.8

**Additional context**
After installing the app or clearing its data the performance is normal, but when I reopen it the performance drops really bad. I think this caused by the new feature [Scan storage on app opens](https://github.com/anilbeesetti/nextplayer/pull/556)

**Comment by anilbeesetti** [comment]
I've reverted that pr. If that is the cause of low performance, it will be fixed in 0.8.1 release. Could you check if app is performing poorly on latest release and let me know

**Comment by obaidabit** [comment]
Yes, As I expected the poor performance was caused by the new feature. now the performance is better.
