### ISSUE TITLE
[Feature request] Support of Network storages

### ISSUE THREAD

**Issue by rnagabhyrava** [anilbeesetti/nextplayer#608]
Support for SMB/NFS would be nice to have.

**Comment by anilbeesetti** [comment]
You can mount smb or NFS in file managers like material files or mixplorer and you can open it in nextplayer

**Comment by plutonium-239** [comment]
> You can mount smb or NFS in file managers like material files or mixplorer and you can open it in nextplayer

How do I do this? I have smb connected in material files but there's no mount option and nextplayer can't see it either. I've also tried CIFS Document Provider, but still nothing.

**Comment by nodejsg** [comment]
> You can mount smb or NFS in file managers like material files or mixplorer and you can open it in nextplayer

While functional, video playback loads extremely slowly and exhibits noticeable stuttering when dragging progress bar, resulting in a poor user experience.
