### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by mateus1619** [anilbeesetti/nextplayer#611]
**Bug description**
App closes when trying to open video from link

**To Reproduce**
1. click on button 'transmission connection'
2. write or paste the link
3. click on button 'done'
4. crash occurs

**Device info:**
 - Device: [Moto E5 play go]
 - Android version: [10]
 - App version: [v0.8.1]

**Comment by anilbeesetti** [comment]
Hey @mateus1619. Is this happening for a specific link or with other video links too. If possible share a screen recording and share the link

**Comment by mateus1619** [comment]
> Hey @mateus1619. Is this happening for a specific link or with other video links too. If possible share a screen recording and share the link

Hey, ASAP!

**Comment by mateus1619** [comment]
@anilbeesetti , Bug fixed
