### ISSUE TITLE
[Feature Request] Auto brightness and Return to list 

### ISSUE THREAD

**Issue by amalka-ari** [anilbeesetti/nextplayer#629]
Love your app, simple, clean and get straight to the point.

I have two feature requests for it.
1. When using swipe for brightness, swipe all the way down (to 0) for auto brightness.
2. Toggle to return to list after playing ended. I've seen this on MX Player. It would be awesome if your player had it.

Thanks
Keep up the good work 👌✌️

**Comment by VasilisKos** [comment]
This is getting closer and closer to MX Player settings chaos... Remember what I told you some months ago @anilbeesetti ?

**Comment by jm355** [comment]
Sorry to bump an old issue, but I'd love to be able to swipe all the way down on brightness to get auto brightness too.
