### ISSUE TITLE
F-Droid listing

### ISSUE THREAD

**Issue by IzzySoft** [anilbeesetti/nextplayer#652]
With your app now listed at F-Droid since 2023-09-12, it would be the time to remove it from my repo (which runs on limited personal space) unless explicitly requested to stay (which would be possible as you've established reproducible builds, so it would not cause confusion for those having both repos enabled). I see your Readme still carries the badge for my repo – so removing the app here would result in a 404, causing some confusion for those following the link. So how shall we proceed?

**Comment by anilbeesetti** [comment]
F-Droid takes long time to show recent builds, while Izzy Droid Repo shows them quicker. So I think it would be best if you keep the Next Player app in your repo.

**Comment by IzzySoft** [comment]
Indeed F-Droid takes at least 3 days for a new version to show up (CheckUpdates + build cycle takes that long), while updates usually reach my repo within 24h.

OK, marked it for "keep" then. Please note that due to its size, currently only the latest 2 versions are kept here – and once the APK size exceeds ~15 MB (it's currently close to that) it will just be a single version in my repo. So when an update is fetched, the previous version will then be purged – which leads to a window of about 24h (default update check interval of the client) in which install/update requests from the client will lead to a 404 then (as the local on-device index points to the purged APK until the index is refreshed). Not an issue yet, just to keep in mind for a potential re-evaluation **then**.
