### ISSUE TITLE
(Discussion) Migrate to Landscapist-Coil

### ISSUE THREAD

**Issue by praveenkumar2K06** [anilbeesetti/nextplayer#655]
@anilbeesetti The Fact that Coil is lightweight compared to Glide since we use only basic function and for the pull request #654 Coil library seems to be better for notification support of artist like this (if the user loads the video from an url)
![Like the background image of LibreTube](https://github.com/anilbeesetti/nextplayer/assets/68219142/0ac2a81a-fc61-483c-8589-042abb4fb1bf)

**Comment by anilbeesetti** [comment]
Currently thumbnail generation is handled by glide, so can't use coil as of now. Once I've added thumbnail generation using ffmpeg then we can look into coil. Ffmpeg thumbnail generation is being worked on currently
