### ISSUE TITLE
[BUG] In automatic (sensor mode) orientation, videos play at wrong aspect when holding phone in portrait mode. 

### ISSUE THREAD

**Issue by Pentaphon** [anilbeesetti/nextplayer#665]
**Describe the bug**
When automatic (sensor mode) orientation setting is set, videos play at wrong aspect when holding phone in portrait mode. 

**To Reproduce**
1. Set to automatic (sensor mode) orientation setting 
2. Play a video 
3. Hold the phone in portrait mode
4. You see this. The video does not fit within the player screen. Just the middle part. 
![Screenshot_20231005-001627](https://github.com/anilbeesetti/nextplayer/assets/49374058/5b914436-1d76-4103-a96c-c4fc857647ee)
 

**Expected behavior**
I expect the video to fit inside the screen when holding the phone in portrait instead of only showing the middle part zoomed in. 

The video should look like this, the way it looks when you hold the phone in landscape mode. 

![Screenshot_20231005-001638](https://github.com/anilbeesetti/nextplayer/assets/49374058/98cdce5b-041e-43f4-8b2f-c360a7fdd2d1)

**Comment by anilbeesetti** [comment]
@Pentaphon what's the zoom mode. Set it to best bit and it will work as expected

**Comment by Pentaphon** [comment]
> @Pentaphon what's the zoom mode. Set it to best bit and it will work as expected

Ah you're right. It does work fine on best bit. Any chance you can make it look right even in another zoom mode or is that not possible? In other words, can you always make the video fit the screen?

**Comment by anilbeesetti** [comment]
@Pentaphon Those modes are supposed be like that. If video is fit at every mode then why bother with all the other modes. Just best fit will be sufficient right

**Comment by Pentaphon** [comment]
Fair enough. Closing.
