### ISSUE TITLE
[Feature]: Balanced crop

### ISSUE THREAD

**Issue by Noitarud** [anilbeesetti/nextplayer#667]
I love math, so I devised a formula to discover the scale required to make the image crop-off area be the same as the black bar area. Would you like to include it in your app?

scale=2xy/(vx+hy)
XY are for screen and HV are for video image.

Nobody's wanted it so far, maybe you can make it pause at that point as the user alters the zoom.

**Comment by anilbeesetti** [comment]
Apologies, @Noitarud, I'm currently utilizing the default zoom options offered by ExoPlayer, and incorporating additional zoom features would require unnecessary effort. It's not required at the moment.
