### ISSUE TITLE
[BUG]: controls system volume when not focussed

### ISSUE THREAD

**Issue by Noitarud** [anilbeesetti/nextplayer#669]
I have another player playing something in background.
I start this program playing,
i need a little more volume so i raise it, but it raises the volume of the other app too!

N.B. another feature you may be able to add at the same time is fractional volume change because there is a big difference bw 0 and 1, sound has a logarithmic scale.

 - Device: Lenovo TB-X505F
 - Android version: 10
 - App version: 0.9.0

**Comment by anilbeesetti** [comment]
This happens because the next player raises the system volume when you increase the volume within the app.

**Comment by Noitarud** [comment]
No? Some apps have a gain adjustment, would that work for NP exclusively?
