### ISSUE TITLE
[BUG] Making player UI more symmetrical.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [anilbeesetti/nextplayer#670]
**Describe the bug**
1. Total runtime should be on the right, like VLC/MX Player.
2. Bottom controls should have total 4 buttons. Two on left, two on right. Or, maybe 3 on left and 3 on right. By bottom controls, I mean, the place that has Lock Video, Video Zoom and Video Orientation.
![Screenshot_2023-10-07-21-33-37-02_8209ce6e823cd719552d7a512aa24e58](https://github.com/anilbeesetti/nextplayer/assets/91815107/d7923e89-a5c5-44b0-a8bc-a74e6e68ea38)

**Device Info :**
 - Device: Realme 7 Pro
 - Android version: 12
 - App version: 0.9 0

**Comment by anilbeesetti** [comment]
The player UI is not finished yet. I have some ideas for the player UI, and once it's completed, you can share your feedback on it.

**Comment by Aryan-Chauhan** [comment]
> The player UI is not finished yet. I have some ideas for the player UI, and once it's completed, you can share your feedback on it.

I didn't realize the player UI is unfinished work... It's okay you closed the issue.
