### ISSUE TITLE
Feature request - background play

### ISSUE THREAD

**Issue by rdrd00** [anilbeesetti/nextplayer#681]
this is very basic feature missing in next player. please provide background play feature.

**Comment by VasilisKos** [comment]
"Next Player is an Android native VIDEO player"

**Comment by Pentaphon** [comment]
Dupe of https://github.com/anilbeesetti/nextplayer/issues/251

**Comment by maribox** [comment]
> "Next Player is an Android native VIDEO player"

Well yeah, and some want to play VIDEOs in the background. On Youtube you even have to pay to get that feature.

**Comment by BierDav** [comment]
This is a legitimate use case for example when you watch a downloaded podcast. Please implement it like YouTube so that you need to opt in in the settings. Not like vlc which makes this task quite tedious

**Comment by Pentaphon** [comment]
@BierDav it looks like this is being worked on in https://github.com/anilbeesetti/nextplayer/pull/1103

This is a duplicate issue so it needs to be closed by @anilbeesetti and further discussion can be had in the pull request or the original issue at https://github.com/anilbeesetti/nextplayer/issues/251

**Comment by anilbeesetti** [comment]
- Done in #1103
