### ISSUE TITLE
[BUG] Problems with autoplay next video feature

### ISSUE THREAD

**Issue by VasilisKos** [anilbeesetti/nextplayer#685]
In an old Alcatel 1S with Android 9, after playing some videos in a row (with the play next video setting active), an error message appears:

![Screenshot_20231010-182336_063330](https://github.com/anilbeesetti/nextplayer/assets/12777771/84f11ac9-c720-4dac-8360-ed033a98015e)

It happens with several random videos. Those videos are normally played when opened individually. So, it probably doesn't have to do with their format, but with the continuous play of several videos, or the old Android version. I'm not sure if this happens with my Nokia with Android 11, because I haven't tried playing many videos in a row.

**Comment by VasilisKos** [comment]
After trying the continuous mode on my Nokia 6.2 with Android 11, I noticed that every video doesn't start from its beginning but from a point of some 10-20 seconds after its start point! 🤔
I even got this error message once:

![Screenshot_20231010-185440](https://github.com/anilbeesetti/nextplayer/assets/12777771/fe89fcf4-7ff1-4e8e-ba92-1763652511b3)

**Comment by VasilisKos** [comment]
After checking again in the Alcatel device, where the videos playlist has longer videos than in my Nokia, I can confirm that every video starts from a random point, not from its beginning. The difference is that in this device I occasionally get the above mentioned error message.
There's definitely something going wrong with the auto play next video feature. That's serious. Needs to be fixed.

**Comment by VasilisKos** [comment]
This doesn't happen when using the next button. Only with auto play next.

**Comment by anilbeesetti** [comment]
It's android surface problem happens when switching from ffmpeg decoder to android mediacodec decoder

**Comment by VasilisKos** [comment]
> It's android surface problem happens when switching from ffmpeg decoder to android mediacodec decoder

So... Any solution?

**Comment by anilbeesetti** [comment]
In theory I can try to use different surface for every video to mitigate this issue. I'm looking into it

**Comment by VasilisKos** [comment]
> In theory I can try to use different surface for every video to mitigate this issue. I'm looking into it

I hope you make it, because otherwise the autoplay feature is pretty much useless.
