### ISSUE TITLE
[Feat] Resume Last Playback Button

### ISSUE THREAD

**Issue by brnwlshubh** [anilbeesetti/nextplayer#687]
Resume Playback Button on Home Screen to resume last left media.

**Comment by Yashraj254** [comment]
@anilbeesetti can i work on this issue?

**Comment by Yashraj254** [comment]
@anilbeesetti does this look fine?


https://github.com/anilbeesetti/nextplayer/assets/52420957/122a137a-3dbe-4810-81a4-4800dd313d18

**Comment by ngocanhtve** [comment]
Absolutely good!

**Comment by anilbeesetti** [comment]
- Implemented in #884
