### ISSUE TITLE
[Feature Request] Silence skipping

### ISSUE THREAD

**Issue by ghost** [anilbeesetti/nextplayer#717]

**Comment by ngocanhtve** [comment]
Like NewPipe one?

**Comment by brnwlshubh** [comment]
#517 Duplicate

**Comment by ghost** [comment]
> #517 Duplicate

yeah but I don't care for it's still worth to restate.

**Comment by ghost** [comment]
> Like NewPipe one?

definitely!

**Comment by ngocanhtve** [comment]
> definitely!

So can we take it from NewPipe and bring it over here?

**Comment by ghost** [comment]
> > definitely!
> 
> So can we take it from NewPipe and bring it over here?

No big deal I guess. IMO it's a must-have feature and there probably dozens of FOSS video players apps out there with this capability. (don't tell me to switch to those apps.)

**Comment by ngocanhtve** [comment]
> No big deal I guess. IMO it's a must-have feature and there probably dozens of FOSS video players apps out there with this capability. (don't tell me to switch to those apps.)

I use NewPipe all the time but don't like this feature.

**Comment by ghost** [comment]
don't enable it then but it saves a lot of time I highly recommend it. what's the problem with ya brother? back me up!

**Comment by ngocanhtve** [comment]
> don't enable it then but it saves a lot of time I highly recommend it. what's the problem with ya brother? back me up!

Yeah, I vote. But I prefer playing at 1.5x rather than skip silence.
