### ISSUE TITLE
[BUG] F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [anilbeesetti/nextplayer#739]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5543063269#L2853

CI APK: https://gitlab.com/fdroid/fdroiddata/-/jobs/5543063269/artifacts/file/tmp/dev.anilbeesetti.nextplayer_13.apk

Difflog: [next13.log](https://github.com/anilbeesetti/nextplayer/files/13367010/next13.log)

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/2e829e9322135acce3664b745ceda43facbbcbec

**Comment by licaon-kter** [comment]
@linsui does the difflog have the same mysterious numbers that you saw the other day?

**Comment by linsui** [comment]
Looks similiar. Maybe it's caused by a update of the libs.

**Comment by anilbeesetti** [comment]
@licaon-kter Is there something i can do or do you guys figured it out

**Comment by licaon-kter** [comment]
Nothing was figured out, we shrugged as we saw a new fail case :(

**Comment by linsui** [comment]
Can you test which update introduces this problem? I thought it's casued by one of the updates in https://github.com/anilbeesetti/nextplayer/compare/v0.10.0...v0.10.1#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87df.

**Comment by anilbeesetti** [comment]
I think it's either kotlin or AGP

**Comment by hegocre** [comment]
I think I can confirm it is caused by kotlin 1.9.20. I took a build that was not reproducible, downgraded the kotlin version, and rebuilt it. It then was reproducible. Now we just have to figure what changed :)

**Comment by licaon-kter** [comment]
What we've figured out, not sure if useful to track anything, is that the difference in magic numbers is constant between your APK and F-Droids

eg.
```
│ │ │ -    const v11, -0x1dcb78a9
│ │ │ +    const v11, -0xd70d666
```
 decimal  `499873961-225498726=274375235` 

except in `dev.anilbeesetti.nextplayer_13/smali/w4/a.smali` where is different for some reason :facepalm:

**Comment by licaon-kter** [comment]
ref: https://gitlab.com/fdroid/fdroiddata/-/issues/3138

**Comment by linsui** [comment]
Please update Compose Compiler to 1.5.6 which should fix the problem. See https://gitlab.com/fdroid/fdroiddata/-/issues/3138
