### ISSUE TITLE
Make the donation process easier (to support development)

### ISSUE THREAD

**Issue by serrq** [anilbeesetti/nextplayer#742]
Please add direct cryptocurrency addresses within the app. Easy tap and donate without leaving the app: I don't want going around to websites. I don't want support FIAT economy.

TRX, AVAX, LTC, BTC, XEC, BNB, SOL, BCH, ALGO, XTZ, DASH, FTM, XMR addresses available for donations (addresses have to be copyable).

![1000092943](https://github.com/anilbeesetti/nextplayer/assets/113377431/9538f489-d88e-4d6b-9a05-17f3368b01d4)

**Comment by anilbeesetti** [comment]
I can't accept cryptocurrencies since in India it has high taxes and not that many exchanges
