### ISSUE TITLE
[BUG] sorting files not in sequence 

### ISSUE THREAD

**Issue by pranavxmeta** [anilbeesetti/nextplayer#755]
**Describe the bug**
The "Media Picker" has minor bug. The file names starts with a number but the sorting is done in wrong way.

For example, (see screenshot) 
- 100.mkv appears just after 10.mkv

- 110.mkv appears just after 11.mkv

Also the videos will play in this order

**To Reproduce**

Rename the files to 10, 11, 100, 110 and check the in app file explorer (Media Picker) 

**Expected behavior**
The files should be properly sorted in correct sequence like 10, 11,... 101, 102,... 110, 111

**Screenshots**
![IMG_20231118_152656.jpg](https://github.com/anilbeesetti/nextplayer/assets/83178186/cd09138a-0737-41c1-b15f-3fdcaf0500a1)

![IMG_20231118_152710.jpg](https://github.com/anilbeesetti/nextplayer/assets/83178186/b664329c-2d42-42e8-b314-ac60b93f1ead)

**Device info (please complete the following information):**
 - Device: [OnePlus 7T]
 - Android version: [12]
 - App version: [ v0.10.1]

**Additional context**
-

**Comment by drogga** [comment]
The same as #491 probably...
