### ISSUE TITLE
Make a lib of Next player

### ISSUE THREAD

**Issue by HiddenPirates** [anilbeesetti/nextplayer#788]
Hi, I want to embed next player in my own app so please make a library for Next player like libVLC has. But LibVLC is too big size. Please a library that we can embed it in our projects as we embed ExoPlayer. But ExoPlayer doesn't support all media formats and can't play all media formats from url.

**Comment by anilbeesetti** [comment]
Checkout NextLib (https://github.com/anilbeesetti/nextlib). It adds software audio and video decoders to exoplayer

**Comment by ThreeMinutesFix** [comment]
thankyou brother
