### ISSUE TITLE
[Bug] Volume increase limited to 100% only instead of 200%

### ISSUE THREAD

**Issue by GunjanSkry** [anilbeesetti/nextplayer#792]
**Description**
I am unable to increase the volume beyond 100% cause I am only getting volume bar limit of 100%, before in older rom I used to get volume bar limit of 200%.

**Steps to Reproduce**
1. Play any video 
2. Just swipe up on right side of the screen 

**Expected behavior**
Volume bar should have limit of 200%

**Screenshots**
![Screenshot_20231214-232350_Next Player](https://github.com/anilbeesetti/nextplayer/assets/31774510/5cc3ecc8-5c28-47d6-9381-f6262039a175)

**Device info**
 - Device: Realme 5 Pro
 - Android version: Evolution x (Android 14)
 - App version: 0.10.1

**Comment by GunjanSkry** [comment]
Can anyone help me to understand why am I not getting audio boost ? how can I debug it to see why am I not getting it ?

**Comment by ABeesettiPaleBlue** [comment]
@GunjanSkry Could you check whether other players support 200% volume?

**Comment by GunjanSkry** [comment]
Sorry, It was my bad , I did flash AOSP sound FX remover and because of that I was not getting audio boost, hence closing the issue.

**Comment by shockergit** [comment]
no its an issue sometimes boost is automatically turned off. after closing and reopening its works ok

**Comment by ShareASmile** [comment]
@anilbeesetti on v0.13.0.rc3 I am unable to increase the volume beyond 100% tried boost setting ON OFF, Restarted player, I am only getting volume bar limit of 100%
Am I the only one facing this or is there a regression in 0.13.0 release candidate 

On stable 0.12.2 I can successfully use volume boost to 200%

**Comment by anilbeesetti** [comment]
> @anilbeesetti on v0.13.0.rc3 I am unable to increase the volume beyond 100% tried boost setting ON OFF, Restarted player, I am only getting volume bar limit of 100%
> Am I the only one facing this or is there a regression in 0.13.0 release candidate 
> 
> On stable 0.12.2 I can successfully use volume boost to 200%

Hey, Will check and fix for the next rc. Let me know if you find any other issues

**Comment by ShareASmile** [comment]
Thanks, yes, I would try. testing release candidate is a good thing before release to minify bugs specially after a lot of big additions.
