### ISSUE TITLE
[BUG] Error when trying resume paused video

### ISSUE THREAD

**Issue by mizzunet** [anilbeesetti/nextplayer#797]
**Describe the bug**
"Can't play video" when I try to resume paused video,  This happens on most of the vidoes

**To Reproduce**
1. Play some video
2. Pause it
3. Resume'

**Expected behavior**
Resume the video

**Screenshots**
![Screenshot_20231218-050624_Evolution X Launcher](https://github.com/anilbeesetti/nextplayer/assets/10193999/d31c885e-5f49-4271-90b6-f01432d77bc1)
![Screenshot_20231218-050553_Evolution X Launcher](https://github.com/anilbeesetti/nextplayer/assets/10193999/674944ee-b7d0-4661-af63-fa99bc45b255)

**Device info (please complete the following information):**
 - Device: Pixel 4a
 - Android version: 14
 - App version: 0.10.1

**Additional context**
Logs
[18_12-05-08-29_953.log.zip](https://github.com/anilbeesetti/nextplayer/files/13698147/18_12-05-08-29_953.log.zip)

**Comment by anilbeesetti** [comment]
@mizzunet. Maybe try this debug build and let me know if the still presists:- https://github.com/anilbeesetti/nextplayer/suites/18908436849/artifacts/1104250034

**Comment by mizzunet** [comment]
Thanks. But I can't test it now because I'm in a tour. I'll try as soon as possible and let you know :)

**Comment by mizzunet** [comment]
I'm afraid, this issue persists.
https://oshi.at/TYLQ


Edit:

Wait, you want me to take logs, don't you?
Here's it is, https://oshi.at/ZYGf

**Comment by mizzunet** [comment]
It appears that the issue happens when "Decoder priority" is either "Device decoders only" or "Prefer device decoder". As far as I tested, it didn't happen when "App decoder" is chosen.

**Comment by mizzunet** [comment]
* Hm, the issue seems with ExoPlayer back end not with Next Player. 
* I'm also getting similar error with Just Player which also use ExoPlayer, not happens on MPV, VLC. https://github.com/google/ExoPlayer/issues/10576
* So, would you add a fallback backend libVLC or libmpv?
