### ISSUE TITLE
[FR] Last played video of a folder

### ISSUE THREAD

**Issue by Sureshgorai25** [anilbeesetti/nextplayer#826]
It is very hard to identify, which video was played last time in a folder. Changing the color of the font maybe useful to find which video was playing last time or now playing. Also a button below will be helpful to play last video fastly.
See MX player for example 

Screenshots
![Screenshot_20240114-193651](https://github.com/anilbeesetti/nextplayer/assets/93507842/9c61eb07-b76d-42e5-9e44-fd9dfeedf9dd)
![Screenshot_20240114-193658](https://github.com/anilbeesetti/nextplayer/assets/93507842/903236d2-1efa-46c5-95e9-e5a4acedc437)

Device info :
 - Device: [Moto G54 5G]
 - Android version: [13]
 - App version: [v10.0.2]

**Comment by Chandidas23** [comment]
Yes waiting for this feature.
