### ISSUE TITLE
[BUG] App flagged as `Trojan`

### ISSUE THREAD

**Issue by vedxp** [anilbeesetti/nextplayer#828]
**Describe the bug**
Next Player is flagged as `Trojan` on Virustotal by `TrendMicro-HouseCall` vendor.

**Device info (please complete the following information):**
 - App version: v0.10.2

**Additional context**
Here's the scan result:
https://www.virustotal.com/gui/file/ffb7167dd1c2f577fa52132c11a767dc6e2ddb3f3131801d194ede0d37502534/summary

**Comment by vedxp** [comment]
Edit: This is happening from version `0.9.0`

**Comment by ABeesettiPaleBlue** [comment]
@vedxp I'm not seeing any vendor flagged nextplayer as Trojan in the link you provided

**Comment by anilbeesetti** [comment]
@vedxp, It looks like flagged as Trojan by mistake. Now it's resolved. Thanks for notifying me
