### ISSUE TITLE
#featurerequest How to integrate Openload subtitle like we do in Mxplayer

### ISSUE THREAD

**Issue by ThreeMinutesFix** [anilbeesetti/nextplayer#846]
Can you add openload subtitle specially create a library or guide me how to add it to exoplayer i am stuck with new version of of API and old version has no doc.

**Comment by anilbeesetti** [comment]
@ThreeMinutesFix I don't know how to do this for certain. I have to research on it for a bit. You can ask on media3 github repo. sure someone will reply
