### ISSUE TITLE
[BUG] Autoplay is a very annoying bug

### ISSUE THREAD

**Issue by mak7im01** [anilbeesetti/nextplayer#874]
**Describe the bug**
Hello, dear developer. I kindly ask you to fix the autoplay. When you turn on autoplay, the video, reaching the end, goes either through the video or even begins to continuously scroll through the video. The switch buttons work properly.

**To Reproduce**
Including. autoplay. I turn on the video, wait for the end and the video scrolls through the next one or starts continuously scrolling the video.

**Expected behavior**
I kindly ask you to correct this error.

**Device info (please complete the following information):**
 - Device: Poco X3 Pro
 - Android version: 11
 - App version: 0.10.2

**Comment by anilbeesetti** [comment]
Hey @mak7im01, Thanks for reporting the issue. It would be helpful if you provide a screen recording of the issue for me look into

**Comment by mak7im01** [comment]
All because of Resume, when turned off, it starts continuously scrolling to the most recent one. When turned on, everything works as it should.

[Screenrecorder.zip](https://github.com/anilbeesetti/nextplayer/files/14735452/Screenrecorder.zip)
Video in ZIP order to reduce the size for GitHub

**Comment by anilbeesetti** [comment]
Hey @mak7im01, Could you check the above changes fixes the issue. Here is the debug apk link:- https://github.com/anilbeesetti/nextplayer/actions/runs/8488206128/artifacts/1371046802

**Comment by mak7im01** [comment]
This problem has disappeared. Thank.

**Comment by Pentaphon** [comment]
@anilbeesetti this can be closed

**Comment by anilbeesetti** [comment]
Thank you @Pentaphon for reminding me.
