### ISSUE TITLE
Feature Request: Ability to add subtitle manually

### ISSUE THREAD

**Issue by shreyas-a-s** [anilbeesetti/nextplayer#879]
Currently subtitle needs to be in the same folder and the same name as video file in order to use it in player. It would be nice to have an option (eg: a + icon in the subtitles menu like in the image below) to manually add a subtitle file.

![Imagepipe_0.jpg](https://github.com/anilbeesetti/nextplayer/assets/137637016/74fac030-7a07-4c37-a034-d16ccf60da37)

**Comment by anilbeesetti** [comment]
Hey @shreyas-a-s, Manual subtitle feature is already there. You just have to long press the subtitle icon. I added a button in the dialog to select subtitles manually instead of long press action just like you suggested to make it more accessible

**Comment by shreyas-a-s** [comment]
Oh I didn't know that feature existed. But now that I test it, it became obvious that it's there. I am able to add subtitles.

And yeah, that addition of a button would be really great since it improves accessibility and visibility of the feature just like you've said.

Plus thanks for the reply coz otherwise I wouldn't have found that the feature is present.

**Comment by shreyas-a-s** [comment]
Hey, Anil. Addition of button is currently in the works or have you already pushed to Github?  Because I couldn't find the commit.

**Comment by anilbeesetti** [comment]
Hey @shreyas-a-s, Already merged to main, https://github.com/anilbeesetti/nextplayer/pull/850

**Comment by shreyas-a-s** [comment]
Ok. Cool. So can I expect it to be included with next release i.e. 0.10.3?

**Comment by shreyas-a-s** [comment]
Cool. 👍🏼
