### ISSUE TITLE
[BUG] Unsupported subtitles

### ISSUE THREAD

**Issue by NikunjK8** [anilbeesetti/nextplayer#880]
**Describe the bug**
I'm using [YTDLnis](https://github.com/deniscerri/ytdlnis) (GUI for yt-dlp) to download videos from YouTube and I've noticed this app can't recognize embedded subtitles of those videos. I've tested them with VLC and MX players and they work fine. Overall this app is solid and check most of the boxes for me but this is a major problem I'm facing. I'm linking a example [video](https://drive.google.com/file/d/1jbyROinh9Y9Wa_1MAq9eQlZD6fU1cvMY/view?usp=drive_link) so you can further investigate and hopefully fix it.

**Screenshots**
![IMG_20240321_160855](https://github.com/anilbeesetti/nextplayer/assets/99175083/58781cc2-84ff-4477-a63d-4084590e1e30)

**Device info (please complete the following information):**
 - Device: [Redmi 9]
 - Android version: [12]
 - App version: [v0.10.2]

**Additional context**

**Comment by moneytoo** [comment]
https://github.com/google/ExoPlayer/issues/11039#issuecomment-1462110423

> The codec ID assigned to this track is D_WEBVTT/SUBTITLES and aligns with http://wiki.webmproject.org/webm-metadata/temporal-metadata/webvtt-in-webm (refer to Storing WebVTT data in a WebM Track).

> At present, MatroskaExtractor only supports WEBVTT for .mkv files, with a codec ID defined as S_TEXT/WEBVTT. As a result, Exoplayer does not recognize this track since we don't support this codec.

**Comment by NikunjK8** [comment]
So basically it can't be fixed until Exoplayer implement it? Well that's sad
