### ISSUE TITLE
Implement played progress in thumbnail 

### ISSUE THREAD

**Issue by max5354** [anilbeesetti/nextplayer#894]
It will be great if you implement video played progress on thumbnail so we can see progress of that played video. For reference you can see in screenshot. I hope you understand and implement it.

![Screenshot_20240330_161247_VLC](https://github.com/anilbeesetti/nextplayer/assets/90886938/6034796e-6538-4797-b552-2f5aa9eea89a)

**Comment by asifahmad134** [comment]
I also recommend to add this feature
