### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [anilbeesetti/nextplayer#927]
My scanner just reported on the latest release:

```
! repo/dev.anilbeesetti.nextplayer_15.apk declares flag(s): usesCleartextTraffic
! repo/dev.anilbeesetti.nextplayer_15.apk declares sensitive permission(s):
  android.permission.READ_MEDIA_VIDEO android.permission.READ_EXTERNAL_STORAGE
```

Now those 2 permissions are clear for a video player, so I've added them to your app's "green list":

![image](https://github.com/anilbeesetti/nextplayer/assets/6781438/ff92737e-4190-4611-864c-289d48f00f3b)

I wouldn't mind to fill the gaps on the remaining permissions if you want to list a short (max ~50 char) explanation for each :wink: (no need for the last one as that's not really a permission but an AndroidX quirk).

I wonder about `usesCleartextTraffic`, though. I assume that is to also play streams from plain `http`. Are those still used much?

**Comment by anilbeesetti** [comment]
Hi @IzzySoft,

`INTERNET` (needed to play online videos)
`WRITE_EXTERNAL_STORAGE` (needed on lower android version for renaming videos and file operations)
`usesCleartextTraffic`   http is still used for home lab stuff (like jellyfin and media servers)

**Comment by IzzySoft** [comment]
Thanks a lot! Added (and live already). Thought exactly about JellyFin & Co there but wasn't sure :smiley:

**Comment by TotallyAvailable** [comment]
***Please*** remember to set the GITHUB_TOKEN permissions (alongside 'persist-credentials', 'Secret Source', triggers, actions used and their pinning, Artifact retention and workflow lifespan) for **all** workflows and across all your projects to the ***absolute minimum*** necessary to avoid further use of **default write-all** tokens.

This message has **nothing** to do with this PR/Issue and should only be seen as a heads-up to reduce the risk of leaking highly privileged tokens in the future. ~~Should this scenario not be of concern, ignore this message.~~ Apologies again for using this way of reaching out.
