### ISSUE TITLE
Google Play version

### ISSUE THREAD

**Issue by VasilisKos** [anilbeesetti/nextplayer#930]
Looks like you forgot to upload the new version on Play...? 😊

**Comment by anilbeesetti** [comment]
I uploaded it on 28 April, but Google is still reviewing the app. ![Screenshot_2024-04-30-17-21-47-930_com.google.android.apps.playconsole.jpg](https://github.com/anilbeesetti/nextplayer/assets/66936649/2004fbd1-513c-47cb-8458-3a3b99bdff8e)

**Comment by VasilisKos** [comment]
What the @#$ are they reviewing for so long? 😋
