### ISSUE TITLE
How do you make a release build in android-studio?

### ISSUE THREAD

**Issue by markg85** [anilbeesetti/nextplayer#932]
Hi,

I'm curious to know the steps to build a release using android studio?
Or just the command line steps you follow to build a release.

When i try a release build it begins to complain about library desugaring (whatever that might be).

**Comment by ABeesettiPaleBlue** [comment]
Hi @markg85, You can just build from android studio wizard. Currently that's how I'm uploading to google play store.

**Comment by anilbeesetti** [comment]
Hi @markg85, You can just build from android studio wizard. Currently that's how I'm uploading to google play store.

**Comment by markg85** [comment]
Ahh, figured out what caused my "library desugaring" issues.
I had "nextlib" cloned in my nextplayer folder and uncommented the config to let the project use that. If you do that debug works, release fails.

While it's not an issue for me anymore, could you look into this? I'd guess that building a release locally (nextlib included) should be possible, no?

Just not using a local nextlib clone made it work for me. I didn't actually need nextlib so it works for me. I do have changes in media3 which i do want to use locally. That works but also fails in a release build though for an whole [different reason](https://github.com/androidx/media/issues/1335).

**Comment by anilbeesetti** [comment]
Hey @markg85, I can build release locally (nextlib included)
![image](https://github.com/anilbeesetti/nextplayer/assets/66936649/0651348a-d0ae-4687-989e-879744315656)

**Comment by markg85** [comment]
It took me a while but i got it working!
Turns out my folder structure was a bit messy. A clean  checkout and actually following to the letter what you said in the code comment is enough to make it work. I had my nextlib inside my nextplayer, not with the same parent.

Closing. Thank you for your help and this great project!
