### ISSUE TITLE
[BUG] Playing any video crashes on Android Go

### ISSUE THREAD

**Issue by DevanWolf** [anilbeesetti/nextplayer#941]
**Describe the bug**
The app is now broken on Android Go devices (possibly Oreo and earlier) on the latest update.

**To Reproduce**
Load any video file or network stream

**Expected behavior**
The video player activity should load properly as in 0.10.2 and earlier.

**Screenshots**

**Device info**
 - Device: VANKYO Z1
 - Android version: Go 8.1 Oreo
 - App version: 0.11.0

**Additional context**
0.10.2 and earlier works fine.

**Comment by ABeesettiPaleBlue** [comment]
Hey @DevanWolf, Sorry for releasing the apk without through testing. Can you check if this apk works:- https://drive.google.com/file/d/1dUWyJvML2IEthd5AZsPGibDGuE5fh_Gq/view?usp=sharing

**Comment by anilbeesetti** [comment]
Hey @DevanWolf, Sorry for releasing the apk without through testing. Can you check if this apk works:- https://drive.google.com/file/d/1dUWyJvML2IEthd5AZsPGibDGuE5fh_Gq/view?usp=sharing

**Comment by DevanWolf** [comment]
> Hey @DevanWolf, Sorry for releasing the apk without through testing. Can you check if this apk works:- https://drive.google.com/file/d/1dUWyJvML2IEthd5AZsPGibDGuE5fh_Gq/view?usp=sharing

Confirmed fixed.
