### ISSUE TITLE
[BUG] Error: can't play video

### ISSUE THREAD

**Issue by demeirgen** [anilbeesetti/nextplayer#982]
Error when trying to play video. 

When opening a file it closes with an error

File information:
![Screenshot_20240630_193758_Next Player.jpg](https://github.com/anilbeesetti/nextplayer/assets/76195431/e8a50595-ccf7-4ad7-8207-2b1cb1a83c56)

 - Device: Samsung Galaxy A52
 - Android version: 14
 - App version: v0.1.1

**Comment by demeirgen** [comment]
When I disable audio track than video start playing. Is there a chance for a fix?

**Comment by Pentaphon** [comment]
@dexaltat You should really be using x264 or x265 mkv files instead. They look better and are smaller. AVI isn't being supported natively by Media3.

**Comment by mirh** [comment]
They do [support](https://github.com/google/ExoPlayer/issues/2092) avi.
And there's also https://github.com/dburckh/Media3Avi

On top of that, I don't know how it could make sense that turning off sound makes a difference here.
