### ISSUE TITLE
Volume control not working.

### ISSUE THREAD

**Issue by ShazidMashrafi** [anilbeesetti/nextplayer#984]
Volume control doesn't seem to work. 
The swipe control to increase and reduce volume doesn't effect volume. It remains constant. The app also doesn't listen to changes in the system volume of android.

 - Device: Redmi note 11
 - Android version: 14
 - App version:  0.11.1

**Comment by anilbeesetti** [comment]
Hey @ShazidMashrafi. Can you send a screen recording for me look into the issue

**Comment by ShazidMashrafi** [comment]
Yeah, about that!
Yesterday, I tried everything (clearing data & reinstalling multiple times from playstore and github too) to get the volume changing. It didn't work. So, I opened an issue.
But, **strangely today it's working**. I couldn't recreate the bug now & don't know what happened in the first place.

Sorry for opening the issue ig and thanks for responding!

**Comment by anilbeesetti** [comment]
No problem, If it happens again open a issue with a screen recording. It will be very helpful for me debug the issue. Thank you
